#!/bin/sh
#-
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2024 The FreeBSD Foundation
#
# This software was developed by Björn Zeeb
# under sponsorship from the FreeBSD Foundation.
#

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

f_dprintf "%s: loading includes..." "$0"
f_include $BSDCFG_SHARE/dialog.subr
f_include $BSDCFG_SHARE/mustberoot.subr
f_include $BSDCFG_SHARE/packages/packages.subr

msg_firmware_installation="$OSNAME Hardware Support"
msg_installer="$OSNAME Installer"
msg_firmware_menu_text="This menu allows you to install drivers and firmware packages for your system"
hline_arrows_space_tab_enter="Use arrows, SPACE, TAB or ENTER"
hline_ok="Press OK to continue"

dialog_menu_main()
{
	local title="$DIALOG_TITLE"
	local btitle="$DIALOG_BACKTITLE"
	local prompt="$msg_firmware_menu_text"
	local hline
	local check_list=	# Empty; filled below
	local fwlist _fw

	fwlist=`chroot $BSDINSTALL_CHROOT fwget -q -n`
	case "${fwlist}" in
	"")	# No additional hardware packages to install
		# Print a dialog with OK and a 3 line timeout bar.
		local height width rows msg

		msg="No additional hardware packages to install, continuing..."
		hline="$hline_ok"

		eval f_dialog_checklist_size height width rows \
			\"\$title\"  \
			\"\$btitle\" \
			\"\$msg\" \
			\"-\"  \
			\"n\"  \
			\"-\" \
			\"\$hline\"

		${DIALOG} --title "${title}" --backtitle "${btitle}" \
		    --hline "${hline}" \
		    --nocancel --pause "${msg}" $height $width 5
		f_dialog_menutag_store -s ""
		return $DIALOG_OK
		;;
	*)
		local desc status height width rows selected retval
		hline="$hline_arrows_space_tab_enter"

		for _fw in ${fwlist}; do
			desc="${_fw}"
			f_shell_escape "$desc" desc
			# install each firmware package by default.
			check_list="$check_list
				'$_fw' '$desc' 'on'
			"
		done

		eval f_dialog_checklist_size height width rows \
			\"\$title\"  \
			\"\$btitle\" \
			\"\$prompt\" \
			\"\$hline\"  \
			$check_list

		selected=$( eval $DIALOG		\
			--title \"\$title\"		\
			--backtitle \"\$btitle\"	\
			--separate-output		\
			--hline \"\$hline\"		\
			--ok-label \"\$msg_ok\"		\
			--cancel-label \"\$msg_cancel\"	\
			--checklist \"\$prompt\"	\
			$height $width $rows		\
			$check_list			\
			2>&1 >&$DIALOG_TERMINAL_PASSTHRU_FD
		)
		retval=$?
		f_dialog_menutag_store -s "$selected"
		return $retval
		;;
	esac
}

# Initialize
f_dialog_title "$msg_firmware_installation"
f_dialog_backtitle "$msg_installer"

# Gather the firmware files and present them to the user
dialog_menu_main || f_die
f_dialog_menutag_fetch selected

firmware_fetch=${BSDINSTALL_FIRMWARE_FETCH:-/usr/libexec/bsdinstall/firmware-fetch}

# Preserve the offline repository even when no device needs extra firmware.
if [ "${selected}" == "" ]; then
	"${firmware_fetch}"
	exit $?
fi

f_mustberoot_init

# Online repositories need name servers; offline installation does not.
if [ -f "$BSDINSTALL_TMPETC/resolv.conf" ]; then
	f_quietly cp -f "$BSDINSTALL_TMPETC/resolv.conf" "$BSDINSTALL_CHROOT/etc/"
fi

${DIALOG} --title "$DIALOG_TITLE" --backtitle "$DIALOG_BACKTITLE" \
	--infobox "Installing drivers and firmware. This may take a moment." 0 0

pkg_install_fail=$(${firmware_fetch} ${selected})
pkg_install_status=$?
if [ ${pkg_install_status} -ne 0 ]; then
	# Error(s) were likely spammed to the console; give the user a moment
	# to read them.
	sleep 5
	bsddialog --backtitle "$OSNAME Installer" --title "Error" \
	    --msgbox "Error installing matching hardware packages$pkg_install_fail" 0 0
		exit 1
fi

# end
