/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only Mesh Sensor model oracles.  Values are transcribed from Mesh
 * Model 1.1 Tables 4.1, 4.11, 4.19-4.36 and Bluetooth Assigned Numbers;
 * this header deliberately has no production includes.
 */

#ifndef TESTS_BLUETOOTH_SPEC_MESH_SENSOR_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_MESH_SENSOR_ORACLES_H

/* Assigned Numbers: Mesh Model identifiers. */
#define BT_MMDL11_SENSOR_SERVER_MODEL_ID	0x1100
#define BT_MMDL11_SENSOR_SETUP_SERVER_MODEL_ID	0x1101
#define BT_MMDL11_SENSOR_CLIENT_MODEL_ID	0x1102

/* Assigned Numbers: Sensor message opcodes. */
#define BT_MMDL11_OP_SENSOR_DESCRIPTOR_GET	0x8230u
#define BT_MMDL11_OP_SENSOR_GET	0x8231u
#define BT_MMDL11_OP_SENSOR_COLUMN_GET	0x8232u
#define BT_MMDL11_OP_SENSOR_SERIES_GET	0x8233u
#define BT_MMDL11_OP_SENSOR_CADENCE_GET	0x8234u
#define BT_MMDL11_OP_SENSOR_SETTINGS_GET	0x8235u
#define BT_MMDL11_OP_SENSOR_SETTING_GET	0x8236u
#define BT_MMDL11_OP_SENSOR_DESCRIPTOR_STATUS	0x51u
#define BT_MMDL11_OP_SENSOR_STATUS	0x52u
#define BT_MMDL11_OP_SENSOR_COLUMN_STATUS	0x53u
#define BT_MMDL11_OP_SENSOR_SERIES_STATUS	0x54u
#define BT_MMDL11_OP_SENSOR_CADENCE_SET	0x55u
#define BT_MMDL11_OP_SENSOR_CADENCE_SET_UNACK	0x56u
#define BT_MMDL11_OP_SENSOR_CADENCE_STATUS	0x57u
#define BT_MMDL11_OP_SENSOR_SETTINGS_STATUS	0x58u
#define BT_MMDL11_OP_SENSOR_SETTING_SET	0x59u
#define BT_MMDL11_OP_SENSOR_SETTING_SET_UNACK	0x5au
#define BT_MMDL11_OP_SENSOR_SETTING_STATUS	0x5bu

/* Mesh Model 1.1 §§4.1.1-4.1.3 and Tables 4.1, 4.11. */
#define BT_MMDL11_SENSOR_DESCRIPTOR_SIZE	8
#define BT_MMDL11_SENSOR_PROPERTY_ID_SIZE	2
#define BT_MMDL11_SENSOR_SETTING_ACCESS_READ	0x01
#define BT_MMDL11_SENSOR_SETTING_ACCESS_READ_WRITE	0x03
#define BT_MMDL11_SENSOR_FAST_DIVISOR_MAX	15
#define BT_MMDL11_SENSOR_MIN_INTERVAL_MAX	26
#define BT_MMDL11_SENSOR_TRIGGER_NATIVE	0
#define BT_MMDL11_SENSOR_TRIGGER_PERCENT	1

/* Mesh Model 1.1 §4.2.14, Tables 4.34-4.36. */
#define BT_MMDL11_SENSOR_MPID_FORMAT_B_TAG	0x01
#define BT_MMDL11_SENSOR_MPID_FORMAT_B_UNKNOWN_HEADER	0xff

#endif /* TESTS_BLUETOOTH_SPEC_MESH_SENSOR_ORACLES_H */
