/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Bluetooth Core 6.3 HCI assignments used by the deep emulator
 * tests.  No production Bluetooth header is included here.
 */
#ifndef TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_DEEP_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_DEEP_ORACLES_H

#include "spec_hci_emulator_link_oracles.h"

/* Vol 4 Part E §§7.1, 7.3.2, 7.4.6, and 7.8 command tables. */
#define HCI_DEEP_SPEC_OP_DISCONNECT		0x0406
#define HCI_DEEP_SPEC_OP_SET_EVENT_MASK		0x0c01
#define HCI_DEEP_SPEC_OP_RESET			0x0c03
#define HCI_DEEP_SPEC_OP_WRITE_LE_HOST_SUPPORTED 0x0c6d
#define HCI_DEEP_SPEC_OP_READ_BDADDR		0x1009
#define HCI_DEEP_SPEC_OP_LE_SET_EVENT_MASK	0x2001
#define HCI_DEEP_SPEC_OP_LE_READ_LOCAL_FEATURES	0x2003
#define HCI_DEEP_SPEC_OP_LE_SET_RANDOM_ADDRESS	0x2005
#define HCI_DEEP_SPEC_OP_LE_SET_ADV_PARAMS	0x2006
#define HCI_DEEP_SPEC_OP_LE_SET_ADV_DATA	0x2008
#define HCI_DEEP_SPEC_OP_LE_SET_SCAN_RSP_DATA	0x2009
#define HCI_DEEP_SPEC_OP_LE_SET_ADV_ENABLE	0x200a
#define HCI_DEEP_SPEC_OP_LE_SET_SCAN_PARAMS	0x200b
#define HCI_DEEP_SPEC_OP_LE_SET_SCAN_ENABLE	0x200c
#define HCI_DEEP_SPEC_OP_LE_CREATE_CONNECTION	0x200d
#define HCI_DEEP_SPEC_OP_LE_CREATE_CONNECTION_CANCEL 0x200e
#define HCI_DEEP_SPEC_OP_LE_ENABLE_ENCRYPTION	0x2019
#define HCI_DEEP_SPEC_OP_LE_LTK_REQ_REPLY	0x201a
#define HCI_DEEP_SPEC_OP_LE_LTK_REQ_NEG_REPLY	0x201b
#define HCI_DEEP_SPEC_OP_LE_ADD_RESOLV		0x2027
#define HCI_DEEP_SPEC_OP_LE_REMOVE_RESOLV	0x2028
#define HCI_DEEP_SPEC_OP_LE_CLEAR_RESOLV	0x2029
#define HCI_DEEP_SPEC_OP_LE_SET_ADDR_RESOLUTION_ENABLE 0x202d
#define HCI_DEEP_SPEC_OP_LE_SET_PERIODIC_ADV_PARAMS 0x203e
#define HCI_DEEP_SPEC_OP_LE_SET_PERIODIC_ADV_RCV_ENABLE 0x2059
#define HCI_DEEP_SPEC_OP_LE_PERIODIC_ADV_SYNC_TRANSFER 0x205a
#define HCI_DEEP_SPEC_OP_LE_READ_BUFFER_SIZE_V2	0x2060
#define HCI_DEEP_SPEC_OP_LE_SET_CIG_PARAMS	0x2062
#define HCI_DEEP_SPEC_OP_LE_READ_REMOTE_TX_POWER 0x2077
#define HCI_DEEP_SPEC_OP_LE_SET_PATH_LOSS_PARAMS 0x2078
#define HCI_DEEP_SPEC_OP_LE_SET_PATH_LOSS_ENABLE 0x2079
#define HCI_DEEP_SPEC_OP_LE_SET_TX_POWER_REPORTING_ENABLE 0x207a
#define HCI_DEEP_SPEC_OP_UNKNOWN_VENDOR		0xffff
#define HCI_DEEP_SPEC_OP_UNKNOWN_LE		0x21ff

/* Vol 1 Part F §2, Controller error-code table. */
#define HCI_DEEP_SPEC_STATUS_SUCCESS		0x00
#define HCI_DEEP_SPEC_STATUS_UNKNOWN_COMMAND	0x01
#define HCI_DEEP_SPEC_STATUS_UNKNOWN_CONNECTION_ID 0x02
#define HCI_DEEP_SPEC_STATUS_PIN_OR_KEY_MISSING	0x06
#define HCI_DEEP_SPEC_STATUS_MEMORY_CAPACITY_EXCEEDED 0x07
#define HCI_DEEP_SPEC_STATUS_COMMAND_DISALLOWED	0x0c
#define HCI_DEEP_SPEC_STATUS_INVALID_PARAMETERS	0x12
#define HCI_DEEP_SPEC_REASON_CONNECTION_TIMEOUT	0x08
#define HCI_DEEP_SPEC_REASON_LOCAL_HOST_TERMINATED 0x16

/* Vol 4 Part E §§7.7.16 and 7.7.65.5. */
#define HCI_DEEP_SPEC_EVENT_HARDWARE_ERROR	0x10
#define HCI_DEEP_SPEC_LEEV_LONG_TERM_KEY_REQUEST 0x05

/* Vol 6 Part B §4.6, Table 4.9 LE feature bit positions. */
#define HCI_DEEP_SPEC_FEAT_PERIODIC_ADV		(UINT64_C(1) << 13)
#define HCI_DEEP_SPEC_FEAT_PAST_SENDER		(UINT64_C(1) << 24)
#define HCI_DEEP_SPEC_FEAT_PAST_RECIPIENT	(UINT64_C(1) << 25)
#define HCI_DEEP_SPEC_FEAT_CIS_CENTRAL		(UINT64_C(1) << 28)
#define HCI_DEEP_SPEC_FEAT_CIS_PERIPHERAL	(UINT64_C(1) << 29)
#define HCI_DEEP_SPEC_FEAT_ISO_BROADCASTER	(UINT64_C(1) << 30)
#define HCI_DEEP_SPEC_FEAT_SYNC_RECEIVER	(UINT64_C(1) << 31)
#define HCI_DEEP_SPEC_FEAT_POWER_CONTROL	(UINT64_C(1) << 33)
#define HCI_DEEP_SPEC_FEAT_PATH_LOSS_MONITORING	(UINT64_C(1) << 35)

/* Vol 4 Part E §7.8.12: Supervision_Timeout is in 10 ms units. */
#define HCI_DEEP_SPEC_SUPERVISION_UNIT_NS	(UINT64_C(10000000))

#endif /* TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_DEEP_ORACLES_H */
