/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Core 6.3 ISO control-plane byte oracles.
 * No production or Netgraph Bluetooth header is included.
 */

#ifndef TESTS_BLUETOOTH_SPEC_ISO_CONTROL_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_ISO_CONTROL_ORACLES_H

/* Core 6.3 Vol 4 Part A §2 Table 2.1; Part E §7.7.14. */
#define BT_ISO_SPEC_EVENT_PACKET		0x04
#define BT_ISO_SPEC_EVENT_COMMAND_COMPLETE	0x0e
#define BT_ISO_SPEC_EVENT_LE_META		0x3e

/* Core 6.3 Vol 4 Part E §§7.8.97 and 7.8.109. */
#define BT_ISO_SPEC_OP_LE_SET_CIG_PARAMS	0x2062
#define BT_ISO_SPEC_OP_LE_SETUP_DATA_PATH	0x206e
#define BT_ISO_SPEC_CIG_HEADER_LEN	15
#define BT_ISO_SPEC_CIS_RECORD_LEN	9
#define BT_ISO_SPEC_CIS_COUNT_MAX	31
#define BT_ISO_SPEC_SETUP_PATH_HEADER_LEN	13
#define BT_ISO_SPEC_DIR_INPUT		0x00
#define BT_ISO_SPEC_DIR_OUTPUT		0x01
#define BT_ISO_SPEC_DATA_PATH_HCI	0x00
#define BT_ISO_SPEC_CODEC_TRANSPARENT	0x03
#define BT_ISO_SPEC_STATUS_SUCCESS	0x00

/* Core 6.3 Vol 4 Part E §§7.7.65.25, 7.7.65.27, 7.7.65.29. */
#define BT_ISO_SPEC_SUBEVENT_CIS_ESTABLISHED	0x19
#define BT_ISO_SPEC_SUBEVENT_CREATE_BIG_COMPLETE	0x1b
#define BT_ISO_SPEC_SUBEVENT_BIG_SYNC_ESTABLISHED	0x1d
#define BT_ISO_SPEC_CIS_ESTABLISHED_PARAM_LEN	28
#define BT_ISO_SPEC_CREATE_BIG_FIXED_LEN	18
#define BT_ISO_SPEC_BIG_SYNC_FIXED_LEN	14

#endif /* TESTS_BLUETOOTH_SPEC_ISO_CONTROL_ORACLES_H */
