/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only Friendship control-message oracles transcribed from Mesh Protocol
 * 1.1 Section 3.6.5, Tables 3.28-3.46.  No production headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_MESH_FRIEND_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_MESH_FRIEND_ORACLES_H

#define BT_MESH11_FRIEND_OP_POLL		0x01
#define BT_MESH11_FRIEND_OP_UPDATE		0x02
#define BT_MESH11_FRIEND_OP_REQUEST		0x03
#define BT_MESH11_FRIEND_OP_OFFER		0x04
#define BT_MESH11_FRIEND_OP_CLEAR		0x05
#define BT_MESH11_FRIEND_OP_CLEAR_CONFIRM	0x06
#define BT_MESH11_FRIEND_OP_SUBLIST_ADD		0x07
#define BT_MESH11_FRIEND_OP_SUBLIST_REMOVE	0x08
#define BT_MESH11_FRIEND_OP_SUBLIST_CONFIRM	0x09

/* Mesh Protocol 1.1 §3.8.6.2, friendship-credential k2 P input. */
#define BT_MESH11_FRIEND_K2_P_SIZE		9

/* Complete unsegmented control PDU sizes: one opcode plus parameters. */
#define BT_MESH11_FRIEND_POLL_PDU_SIZE		2
#define BT_MESH11_FRIEND_UPDATE_PDU_SIZE	7
#define BT_MESH11_FRIEND_REQUEST_PDU_SIZE	11
#define BT_MESH11_FRIEND_OFFER_PDU_SIZE		7
#define BT_MESH11_FRIEND_CLEAR_PDU_SIZE		5
#define BT_MESH11_FRIEND_CLEAR_CONFIRM_PDU_SIZE	5
#define BT_MESH11_FRIEND_SUBCONFIRM_PDU_SIZE	2

/* Tables 3.32-3.38: Criteria and Friend Request field bounds. */
#define BT_MESH11_FRIEND_RSSI_FACTOR_MAX	3
#define BT_MESH11_FRIEND_RX_WINDOW_FACTOR_MAX	3
#define BT_MESH11_FRIEND_MIN_QUEUE_LOG_MIN	1
#define BT_MESH11_FRIEND_MIN_QUEUE_LOG_MAX	7
#define BT_MESH11_FRIEND_RECEIVE_DELAY_MIN_MS	0x0a
#define BT_MESH11_FRIEND_POLL_TIMEOUT_MIN	0x00000au
#define BT_MESH11_FRIEND_POLL_TIMEOUT_MAX	0x34bbffu
#define BT_MESH11_FRIEND_SUBLIST_ADDR_MAX	16

#endif /* TESTS_BLUETOOTH_SPEC_MESH_FRIEND_ORACLES_H */
