/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only HCI emulator oracles from Bluetooth Core 6.3 Vol 4 Part A
 * §2/Table 2.1 and Vol 4 Part E §§5.4.2, 7.8.7, 7.8.9, 7.8.11-7.8.12.
 * No production headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_FAULT_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_FAULT_ORACLES_H

#define BT_CORE63_HCI_COMMAND_PACKET	0x01
#define BT_CORE63_HCI_ACL_PACKET		0x02
#define BT_CORE63_HCI_OGF_LE		0x08
#define BT_CORE63_HCI_OCF_LE_SET_ADV_DATA	0x0008
#define BT_CORE63_HCI_OCF_LE_SET_ADV_ENABLE	0x000a
#define BT_CORE63_HCI_OCF_LE_SET_SCAN_ENABLE	0x000c
#define BT_CORE63_HCI_OCF_LE_CREATE_CONNECTION	0x000d
#define BT_CORE63_HCI_ACL_PB_FIRST_NONFLUSH	0x0
#define BT_CORE63_HCI_ACL_BC_POINT_TO_POINT	0x0
#define BT_CORE63_HCI_ACL_HANDLE_MASK	0x0fff
#define BT_CORE63_HCI_ACL_HEADER_SIZE	5
#define BT_CORE63_LE_CREATE_CONNECTION_PARAM_SIZE 25

#endif /* TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_FAULT_ORACLES_H */
