/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only privacy/HCI oracles from Bluetooth Core 6.3 Vol 4 Part E
 * §§7.8.10, 7.8.44-7.8.45.  No production or Netgraph headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_PRIVACY_SCAN_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_PRIVACY_SCAN_ORACLES_H

#define BT_CORE63_HCI_OGF_LE			0x08
#define BT_CORE63_HCI_OCF_LE_SET_SCAN_PARAMETERS	0x000b
#define BT_CORE63_HCI_OCF_LE_SET_ADDR_RES_ENABLE	0x002d
#define BT_CORE63_HCI_OCF_LE_SET_RPA_TIMEOUT	0x002e

/* Exact 16-bit HCI command opcodes: (OGF << 10) | OCF. */
#define BT_CORE63_HCI_OP_LE_SET_SCAN_PARAMETERS	0x200b
#define BT_CORE63_HCI_OP_LE_SET_ADDR_RES_ENABLE	0x202d
#define BT_CORE63_HCI_OP_LE_SET_RPA_TIMEOUT	0x202e

#define BT_CORE63_ADDR_RESOLUTION_DISABLED	0x00
#define BT_CORE63_ADDR_RESOLUTION_ENABLED	0x01
#define BT_CORE63_OWN_ADDR_PUBLIC		0x00
#define BT_CORE63_OWN_ADDR_RPA_PUBLIC_FALLBACK	0x02

#define BT_CORE63_RPA_TIMEOUT_MIN_SECONDS	0x0001
#define BT_CORE63_RPA_TIMEOUT_DEFAULT_SECONDS	0x0384
#define BT_CORE63_RPA_TIMEOUT_MAX_SECONDS	0x0e10
#define BT_CORE63_RPA_TIMEOUT_BELOW_MIN		0x0000
#define BT_CORE63_RPA_TIMEOUT_ABOVE_MAX		0x0e11

#define BT_CORE63_SET_ADDR_RES_ENABLE_PARAM_SIZE	1
#define BT_CORE63_SET_RPA_TIMEOUT_PARAM_SIZE	2
#define BT_CORE63_SET_SCAN_PARAMETERS_PARAM_SIZE	7
#define BT_CORE63_SCAN_OWN_ADDR_TYPE_OFFSET	5

#endif /* TESTS_BLUETOOTH_SPEC_PRIVACY_SCAN_ORACLES_H */
