/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Core 6.3 byte assignments for hci_emulator_link_test.
 * This header includes no production Bluetooth headers.
 */

#ifndef TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_LINK_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_LINK_ORACLES_H

#include "spec_core63_generated.h"

#define HCI_LINK_SPEC_ENUM(name, value) HCI_LINK_SPEC_##name = value,
enum {
	BT_CORE63_HCI_EVENT_ORACLES(HCI_LINK_SPEC_ENUM)
	BT_CORE63_HCI_LE_SUBEVENT_ORACLES(HCI_LINK_SPEC_ENUM)
	BT_CORE63_HCI_PACKET_ORACLES(HCI_LINK_SPEC_ENUM)
};
#undef HCI_LINK_SPEC_ENUM

/* Core 6.3 Vol 4 Part A §2, Table 2.1. */
#define HCI_LINK_SPEC_CMD_PKT		0x01
#define HCI_LINK_SPEC_ACL_PKT		0x02

/* Core 6.3 Vol 4 Part E §§7.1.6 and 7.8.5-7.8.14. */
#define HCI_LINK_SPEC_OP_DISCONNECT	0x0406
#define HCI_LINK_SPEC_OP_LE_SET_ADV_PARAMS	0x2006
#define HCI_LINK_SPEC_OP_LE_SET_ADV_DATA	0x2008
#define HCI_LINK_SPEC_OP_LE_SET_ADV_ENABLE	0x200a
#define HCI_LINK_SPEC_OP_LE_SET_SCAN_ENABLE	0x200c
#define HCI_LINK_SPEC_OP_LE_CREATE_CONNECTION	0x200d
#define HCI_LINK_SPEC_OP_LE_CREATE_CONNECTION_CANCEL	0x200e

/* Core 6.3 Vol 4 Part E §5.4.2. */
#define HCI_LINK_SPEC_HANDLE_MASK	0x0fff
#define HCI_LINK_SPEC_PB_SHIFT		12
#define HCI_LINK_SPEC_BC_SHIFT		14
#define HCI_LINK_SPEC_FLAG_MASK		0x03
#define HCI_LINK_SPEC_LE_PACKET_START	0x00
#define HCI_LINK_SPEC_POINT_TO_POINT	0x00
#define HCI_LINK_SPEC_ACL_HEADER_LEN	5
#define HCI_LINK_SPEC_MAKE_HANDLE(h, pb, bc) \
	(((h) & HCI_LINK_SPEC_HANDLE_MASK) | \
	 (((pb) & HCI_LINK_SPEC_FLAG_MASK) << HCI_LINK_SPEC_PB_SHIFT) | \
	 (((bc) & HCI_LINK_SPEC_FLAG_MASK) << HCI_LINK_SPEC_BC_SHIFT))
#define HCI_LINK_SPEC_HANDLE(v)	((v) & HCI_LINK_SPEC_HANDLE_MASK)
#define HCI_LINK_SPEC_PB(v) \
	(((v) >> HCI_LINK_SPEC_PB_SHIFT) & HCI_LINK_SPEC_FLAG_MASK)

/* Core 6.3 Vol 4 Part E event and role/status parameter tables. */
#define HCI_LINK_SPEC_STATUS_SUCCESS	0x00
#define HCI_LINK_SPEC_STATUS_UNKNOWN_CONNECTION_ID	0x02
#define HCI_LINK_SPEC_ROLE_CENTRAL	0x00
#define HCI_LINK_SPEC_ROLE_PERIPHERAL	0x01
#define HCI_LINK_SPEC_ADDR_PUBLIC	0x00
#define HCI_LINK_SPEC_CLOCK_ACCURACY_251_TO_500_PPM	0x00
#define HCI_LINK_SPEC_ADV_REPORT_ADV_IND	0x00
#define HCI_LINK_SPEC_ADV_REPORT_DIRECT_IND	0x01
#define HCI_LINK_SPEC_CONN_COMPLETE_PARAM_LEN	19
#define HCI_LINK_SPEC_COMMAND_STATUS_PARAM_LEN	4
#define HCI_LINK_SPEC_NCP_PARAM_LEN	5
#define HCI_LINK_SPEC_DISCON_COMPLETE_PARAM_LEN	4
#define HCI_LINK_SPEC_REASON_REMOTE_USER_TERM	0x13
#define HCI_LINK_SPEC_REASON_LOCAL_HOST_TERM	0x16

#endif /* TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_LINK_ORACLES_H */
