/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Core 6.3 ATT/GATT and SIG profile assignments for profile data.
 * No production Bluetooth header is included.
 */

#ifndef TESTS_BLUETOOTH_SPEC_PROFILE_DATA_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_PROFILE_DATA_ORACLES_H

/* Core 6.3 Vol 3 Part F §3.4 request/response opcodes. */
#define BT_PROFILE_SPEC_ATT_ERROR_RSP		0x01
#define BT_PROFILE_SPEC_ATT_FIND_INFO_RSP	0x05
#define BT_PROFILE_SPEC_ATT_READ_BY_TYPE_REQ	0x08
#define BT_PROFILE_SPEC_ATT_READ_BY_TYPE_RSP	0x09
#define BT_PROFILE_SPEC_ATT_READ_REQ		0x0a
#define BT_PROFILE_SPEC_ATT_READ_RSP		0x0b
#define BT_PROFILE_SPEC_ATT_READ_BY_GROUP_RSP	0x11
#define BT_PROFILE_SPEC_ATT_WRITE_REQ		0x12
#define BT_PROFILE_SPEC_ATT_WRITE_RSP		0x13
#define BT_PROFILE_SPEC_ATT_HANDLE_NOTIFY	0x1b

/* Core 6.3 Vol 3 Part F §3.4.1.1 Table 3.4. */
#define BT_PROFILE_SPEC_ERR_READ_NOT_PERMITTED	0x02
#define BT_PROFILE_SPEC_ERR_VALUE_NOT_ALLOWED	0x13

/* Core 6.3 Vol 3 Part G §§3.2-3.3 and 7.3. */
#define BT_PROFILE_SPEC_UUID_PRIMARY_SERVICE	0x2800
#define BT_PROFILE_SPEC_UUID_CHARACTERISTIC	0x2803
#define BT_PROFILE_SPEC_UUID_CCCD		0x2902
#define BT_PROFILE_SPEC_UUID_REPORT_REFERENCE	0x2908
#define BT_PROFILE_SPEC_UUID_DATABASE_HASH	0x2b2a
#define BT_PROFILE_SPEC_PROP_READ		0x02
#define BT_PROFILE_SPEC_PROP_WRITE_NO_RSP	0x04
#define BT_PROFILE_SPEC_PROP_NOTIFY		0x10
#define BT_PROFILE_SPEC_PROP_INDICATE		0x20

/* Bluetooth SIG Assigned Numbers: profile service and characteristic UUIDs. */
#define BT_PROFILE_SPEC_UUID_GAP_SERVICE	0x1800
#define BT_PROFILE_SPEC_UUID_GATT_SERVICE	0x1801
#define BT_PROFILE_SPEC_UUID_HEART_RATE_SERVICE	0x180d
#define BT_PROFILE_SPEC_UUID_DIS_SERVICE	0x180a
#define BT_PROFILE_SPEC_UUID_BATTERY_SERVICE	0x180f
#define BT_PROFILE_SPEC_UUID_HID_SERVICE	0x1812
#define BT_PROFILE_SPEC_UUID_DEVICE_NAME	0x2a00
#define BT_PROFILE_SPEC_UUID_APPEARANCE		0x2a01
#define BT_PROFILE_SPEC_UUID_SERVICE_CHANGED	0x2a05
#define BT_PROFILE_SPEC_UUID_BATTERY_LEVEL	0x2a19
#define BT_PROFILE_SPEC_UUID_MODEL_NUMBER	0x2a24
#define BT_PROFILE_SPEC_UUID_FIRMWARE_REV	0x2a26
#define BT_PROFILE_SPEC_UUID_MANUFACTURER	0x2a29
#define BT_PROFILE_SPEC_UUID_HR_MEASUREMENT	0x2a37
#define BT_PROFILE_SPEC_UUID_BODY_SENSOR_LOC	0x2a38
#define BT_PROFILE_SPEC_UUID_HID_INFORMATION	0x2a4a
#define BT_PROFILE_SPEC_UUID_REPORT_MAP		0x2a4b
#define BT_PROFILE_SPEC_UUID_REPORT		0x2a4d
#define BT_PROFILE_SPEC_UUID_PROTOCOL_MODE	0x2a4e

#endif /* TESTS_BLUETOOTH_SPEC_PROFILE_DATA_ORACLES_H */
