/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2007 Roman Divacky
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#ifndef _LINUX_FILE_H_
#define	_LINUX_FILE_H_

#define	LINUX_AT_FDCWD			-100
#define	LINUX_AT_SYMLINK_NOFOLLOW	0x100
#define	LINUX_AT_EACCESS		0x200
#define	LINUX_AT_REMOVEDIR		0x200
#define	LINUX_AT_SYMLINK_FOLLOW		0x400
#define	LINUX_AT_NO_AUTOMOUNT		0x800
		/*
		 * Specific to Linux AT_NO_AUTOMOUNT flag tells the kernel to
		 * not automount the terminal component of pathname if it is a
		 * directory that is an automount point. As FreeBSD does not
		 * have such facility (automount), we can simply ignore this flag.
		 */
#define	LINUX_AT_EMPTY_PATH		0x1000
#define	LINUX_AT_STATX_SYNC_TYPE	0x6000
#define	LINUX_AT_STATX_SYNC_AS_STAT	0x0000
#define	LINUX_AT_STATX_FORCE_SYNC	0x2000
#define	LINUX_AT_STATX_DONT_SYNC	0x4000

/* extended-attribute operation flags */
#define	LINUX_XATTR_CREATE		0x1
#define	LINUX_XATTR_REPLACE		0x2
#define	LINUX_XATTR_FLAGS		(LINUX_XATTR_CREATE | LINUX_XATTR_REPLACE)

/*
 * posix_fadvise advice
 */
#define	LINUX_POSIX_FADV_NORMAL		0
#define	LINUX_POSIX_FADV_RANDOM		1
#define	LINUX_POSIX_FADV_SEQUENTIAL	2
#define	LINUX_POSIX_FADV_WILLNEED	3
#define	LINUX_POSIX_FADV_DONTNEED	4
#define	LINUX_POSIX_FADV_NOREUSE	5

/*
 * mount flags
 */
#define	LINUX_MS_RDONLY		0x0001
#define	LINUX_MS_NOSUID		0x0002
#define	LINUX_MS_NODEV		0x0004
#define	LINUX_MS_NOEXEC		0x0008
#define	LINUX_MS_REMOUNT	0x0020
#define	LINUX_MS_SYNCHRONOUS	0x0010
#define	LINUX_MS_MANDLOCK	0x0040
#define	LINUX_MS_DIRSYNC	0x0080
#define	LINUX_MS_NOSYMFOLLOW	0x0100
#define	LINUX_MS_NOATIME	0x0400
#define	LINUX_MS_NODIRATIME	0x0800
#define	LINUX_MS_BIND		0x1000
#define	LINUX_MS_MOVE		0x2000
#define	LINUX_MS_REC		0x4000
#define	LINUX_MS_SILENT		0x8000
#define	LINUX_MS_POSIXACL	(1 << 16)
#define	LINUX_MS_UNBINDABLE	(1 << 17)
#define	LINUX_MS_PRIVATE	(1 << 18)
#define	LINUX_MS_SLAVE		(1 << 19)
#define	LINUX_MS_SHARED		(1 << 20)
#define	LINUX_MS_RELATIME	(1 << 21)
#define	LINUX_MS_I_VERSION	(1 << 23)
#define	LINUX_MS_STRICTATIME	(1 << 24)
#define	LINUX_MS_LAZYTIME	(1 << 25)
#define	LINUX_MS_PROPAGATION	(LINUX_MS_UNBINDABLE | LINUX_MS_PRIVATE | \
	LINUX_MS_SLAVE | LINUX_MS_SHARED)
#define	LINUX_MS_MGC_VAL	0xC0ED0000
#define	LINUX_MS_MGC_MSK	0xffff0000

/*
 * umount2 flags
 */
#define	LINUX_MNT_FORCE		0x0001
#define	LINUX_MNT_DETACH	0x0002
#define	LINUX_MNT_EXPIRE	0x0004
#define	LINUX_UMOUNT_NOFOLLOW	0x0008

/*
 * common open/fcntl flags
 */
#define	LINUX_O_RDONLY		000000000
#define	LINUX_O_WRONLY		000000001
#define	LINUX_O_RDWR		000000002
#define	LINUX_O_ACCMODE		000000003
#define	LINUX_O_CREAT		000000100
#define	LINUX_O_EXCL		000000200
#define	LINUX_O_NOCTTY		000000400
#define	LINUX_O_TRUNC		000001000
#define	LINUX_O_APPEND		000002000
#define	LINUX_O_NONBLOCK	000004000
#define	LINUX_O_NDELAY		LINUX_O_NONBLOCK
#define	LINUX_O_DSYNC		000010000
#define	LINUX_O_SYNC		(LINUX___O_SYNC | LINUX_O_DSYNC)
#define	LINUX_O_ASYNC		000020000
#ifndef LINUX_O_DIRECT
#define	LINUX_O_DIRECT		000040000	/* Direct disk access hint */
#endif
#ifndef LINUX_O_LARGEFILE
#define	LINUX_O_LARGEFILE	000100000
#endif
#ifndef LINUX_O_DIRECTORY
#define	LINUX_O_DIRECTORY	000200000	/* Must be a directory */
#endif
#ifndef LINUX_O_NOFOLLOW
#define	LINUX_O_NOFOLLOW	000400000	/* Do not follow links */
#endif
#define	LINUX_O_NOATIME		001000000
#define	LINUX_O_CLOEXEC		002000000
#define	LINUX___O_SYNC		004000000
#define	LINUX_O_PATH		010000000
#define	LINUX___O_TMPFILE	020000000
#define	LINUX_O_TMPFILE		(LINUX___O_TMPFILE | LINUX_O_DIRECTORY)

/*
 * openat2(2): struct open_how and RESOLVE_* flags.
 */
struct l_open_how {
	uint64_t	flags;
	uint64_t	mode;
	uint64_t	resolve;
};
#define	LINUX_OPEN_HOW_SIZE_VER0	24
#define	LINUX_OPEN_HOW_SIZE_LATEST	LINUX_OPEN_HOW_SIZE_VER0

#define	LINUX_RESOLVE_NO_XDEV		0x01
#define	LINUX_RESOLVE_NO_MAGICLINKS	0x02
#define	LINUX_RESOLVE_NO_SYMLINKS	0x04
#define	LINUX_RESOLVE_BENEATH		0x08
#define	LINUX_RESOLVE_IN_ROOT		0x10
#define	LINUX_RESOLVE_CACHED		0x20

/*
 * file_getattr(2)/file_setattr(2), added in Linux 6.17.  The structure is
 * explicitly sized in the ABI and has the same layout on every supported
 * Linux architecture.
 */
struct l_file_attr {
	uint64_t	fa_xflags;
	uint32_t	fa_extsize;
	uint32_t	fa_nextents;
	uint32_t	fa_projid;
	uint32_t	fa_cowextsize;
};
#define	LINUX_FILE_ATTR_SIZE_VER0	24

#define	LINUX_FS_XFLAG_REALTIME		0x00000001
#define	LINUX_FS_XFLAG_PREALLOC		0x00000002
#define	LINUX_FS_XFLAG_IMMUTABLE	0x00000008
#define	LINUX_FS_XFLAG_APPEND		0x00000010
#define	LINUX_FS_XFLAG_SYNC		0x00000020
#define	LINUX_FS_XFLAG_NOATIME		0x00000040
#define	LINUX_FS_XFLAG_NODUMP		0x00000080
#define	LINUX_FS_XFLAG_RTINHERIT	0x00000100
#define	LINUX_FS_XFLAG_PROJINHERIT	0x00000200
#define	LINUX_FS_XFLAG_NOSYMLINKS	0x00000400
#define	LINUX_FS_XFLAG_EXTSIZE		0x00000800
#define	LINUX_FS_XFLAG_EXTSZINHERIT	0x00001000
#define	LINUX_FS_XFLAG_NODEFRAG		0x00002000
#define	LINUX_FS_XFLAG_FILESTREAM	0x00004000
#define	LINUX_FS_XFLAG_DAX		0x00008000
#define	LINUX_FS_XFLAG_COWEXTSIZE	0x00010000
#define	LINUX_FS_XFLAG_VERITY		0x00020000
#define	LINUX_FS_XFLAG_CASEFOLD		0x00040000
#define	LINUX_FS_XFLAG_CASENONPRESERVING 0x00080000
#define	LINUX_FS_XFLAG_HASATTR		0x80000000

#define	LINUX_FS_XFLAG_RDONLY_MASK	(				\
	LINUX_FS_XFLAG_PREALLOC | LINUX_FS_XFLAG_HASATTR |		\
	LINUX_FS_XFLAG_VERITY | LINUX_FS_XFLAG_CASEFOLD |		\
	LINUX_FS_XFLAG_CASENONPRESERVING)
#define	LINUX_FS_XFLAGS_MASK	(					\
	LINUX_FS_XFLAG_REALTIME | LINUX_FS_XFLAG_PREALLOC |		\
	LINUX_FS_XFLAG_IMMUTABLE | LINUX_FS_XFLAG_APPEND |		\
	LINUX_FS_XFLAG_SYNC | LINUX_FS_XFLAG_NOATIME |			\
	LINUX_FS_XFLAG_NODUMP | LINUX_FS_XFLAG_RTINHERIT |		\
	LINUX_FS_XFLAG_PROJINHERIT | LINUX_FS_XFLAG_NOSYMLINKS |	\
	LINUX_FS_XFLAG_EXTSIZE | LINUX_FS_XFLAG_EXTSZINHERIT |		\
	LINUX_FS_XFLAG_NODEFRAG | LINUX_FS_XFLAG_FILESTREAM |		\
	LINUX_FS_XFLAG_DAX | LINUX_FS_XFLAG_COWEXTSIZE |		\
	LINUX_FS_XFLAG_VERITY | LINUX_FS_XFLAG_CASEFOLD |		\
	LINUX_FS_XFLAG_CASENONPRESERVING | LINUX_FS_XFLAG_HASATTR)
#define	LINUX_FS_XFLAG_SUPPORTED	(				\
	LINUX_FS_XFLAG_IMMUTABLE | LINUX_FS_XFLAG_APPEND |		\
	LINUX_FS_XFLAG_NODUMP)

#define	LINUX_F_DUPFD		0
#define	LINUX_F_GETFD		1
#define	LINUX_F_SETFD		2
#define	LINUX_F_GETFL		3
#define	LINUX_F_SETFL		4
#ifndef LINUX_F_GETLK
#define	LINUX_F_GETLK		5
#define	LINUX_F_SETLK		6
#define	LINUX_F_SETLKW		7
#endif
#ifndef LINUX_F_SETOWN
#define	LINUX_F_SETOWN		8
#define	LINUX_F_GETOWN		9
#endif
#ifndef LINUX_F_SETSIG
#define	LINUX_F_SETSIG		10
#define	LINUX_F_GETSIG		11
#endif
#ifndef LINUX_F_SETOWN_EX
#define	LINUX_F_SETOWN_EX	15
#define	LINUX_F_GETOWN_EX	16
#define	LINUX_F_GETOWNER_UIDS	17
#endif

#define	LINUX_F_SPECIFIC_BASE	1024

#define	LINUX_F_SETLEASE	(LINUX_F_SPECIFIC_BASE + 0)
#define	LINUX_F_GETLEASE	(LINUX_F_SPECIFIC_BASE + 1)
#define	LINUX_F_DUPFD_QUERY	(LINUX_F_SPECIFIC_BASE + 3)
#define	LINUX_F_CANCELLK	(LINUX_F_SPECIFIC_BASE + 5)
#define	LINUX_F_DUPFD_CLOEXEC	(LINUX_F_SPECIFIC_BASE + 6)
#define	LINUX_F_NOTIFY		(LINUX_F_SPECIFIC_BASE + 2)
#define	LINUX_F_SETPIPE_SZ	(LINUX_F_SPECIFIC_BASE + 7)
#define	LINUX_F_GETPIPE_SZ	(LINUX_F_SPECIFIC_BASE + 8)

#define	LINUX_F_ADD_SEALS	(LINUX_F_SPECIFIC_BASE + 9)
#define	LINUX_F_GET_SEALS	(LINUX_F_SPECIFIC_BASE + 10)
#define	LINUX_F_CREATED_QUERY	(LINUX_F_SPECIFIC_BASE + 4)
#define	LINUX_F_GET_RW_HINT	(LINUX_F_SPECIFIC_BASE + 11)
#define	LINUX_F_SET_RW_HINT	(LINUX_F_SPECIFIC_BASE + 12)
#define	LINUX_F_GET_FILE_RW_HINT (LINUX_F_SPECIFIC_BASE + 13)
#define	LINUX_F_SET_FILE_RW_HINT (LINUX_F_SPECIFIC_BASE + 14)
#define	LINUX_F_GETDELEG	(LINUX_F_SPECIFIC_BASE + 15)
#define	LINUX_F_SETDELEG	(LINUX_F_SPECIFIC_BASE + 16)

#define	LINUX_RWH_WRITE_LIFE_NOT_SET	0
#define	LINUX_RWH_WRITE_LIFE_EXTREME	5

/* splice(2)/vmsplice(2) flags. */
#define	LINUX_SPLICE_F_MOVE	0x01
#define	LINUX_SPLICE_F_NONBLOCK	0x02
#define	LINUX_SPLICE_F_MORE	0x04
#define	LINUX_SPLICE_F_GIFT	0x08
#define	LINUX_SPLICE_F_ALL	0x0f
#define	LINUX_SPLICE_CHUNK	(64 * 1024)

/* preadv2(2)/pwritev2(2) flags. */
#define	LINUX_RWF_HIPRI		0x0001
#define	LINUX_RWF_DSYNC		0x0002
#define	LINUX_RWF_SYNC		0x0004
#define	LINUX_RWF_NOWAIT	0x0008
#define	LINUX_RWF_APPEND	0x0010
#define	LINUX_RWF_NOAPPEND	0x0020
#define	LINUX_RWF_ATOMIC	0x0040
#define	LINUX_RWF_DONTCACHE	0x0080
#define	LINUX_RWF_NOSIGNAL	0x0100
#define	LINUX_RWF_SUPPORTED	0x01ff

int linux_rwf_flags(uint32_t flags, int *foflags);

/* fallocate(2) modes. */
#define	LINUX_FALLOC_FL_KEEP_SIZE	0x01
#define	LINUX_FALLOC_FL_PUNCH_HOLE	0x02
#define	LINUX_FALLOC_FL_NO_HIDE_STALE	0x04
#define	LINUX_FALLOC_FL_COLLAPSE_RANGE	0x08
#define	LINUX_FALLOC_FL_ZERO_RANGE	0x10
#define	LINUX_FALLOC_FL_INSERT_RANGE	0x20
#define	LINUX_FALLOC_FL_UNSHARE_RANGE	0x40
#define	LINUX_FALLOC_FL_WRITE_ZEROES	0x80
#define	LINUX_FALLOC_FL_SUPPORTED	(LINUX_FALLOC_FL_KEEP_SIZE |	\
	LINUX_FALLOC_FL_PUNCH_HOLE | LINUX_FALLOC_FL_COLLAPSE_RANGE |	\
	LINUX_FALLOC_FL_ZERO_RANGE | LINUX_FALLOC_FL_INSERT_RANGE |	\
	LINUX_FALLOC_FL_UNSHARE_RANGE | LINUX_FALLOC_FL_WRITE_ZEROES)

#define	LINUX_F_GETLKP		36
#define	LINUX_F_SETLKP		37
#define	LINUX_F_SETLKPW		38
#define	LINUX_F_OFD_GETLK	LINUX_F_GETLKP
#define	LINUX_F_OFD_SETLK	LINUX_F_SETLKP
#define	LINUX_F_OFD_SETLKW	LINUX_F_SETLKPW

#define	LINUX_F_OWNER_TID	0
#define	LINUX_F_OWNER_PID	1
#define	LINUX_F_OWNER_PGRP	2

/* F_SETOWN_EX / F_GETOWN_EX argument. */
struct l_f_owner_ex {
	l_int	type;
	l_pid_t	pid;
};

#ifndef LINUX_F_RDLCK
#define	LINUX_F_RDLCK		0
#define	LINUX_F_WRLCK		1
#define	LINUX_F_UNLCK		2
#endif

/*
 * renameat2 flags
 */
#define	LINUX_RENAME_NOREPLACE	0x00000001
#define	LINUX_RENAME_EXCHANGE	0x00000002
#define	LINUX_RENAME_WHITEOUT	0x00000004

/*
 * sync_file_range flags
 */
#define	LINUX_SYNC_FILE_RANGE_WAIT_BEFORE	1
#define	LINUX_SYNC_FILE_RANGE_WRITE		2
#define	LINUX_SYNC_FILE_RANGE_WAIT_AFTER	4

#define	LINUX_F_SEAL_SEAL	0x0001
#define	LINUX_F_SEAL_SHRINK	0x0002
#define	LINUX_F_SEAL_GROW	0x0004
#define	LINUX_F_SEAL_WRITE	0x0008
#define	LINUX_F_SEAL_FUTURE_WRITE 0x0010
#define	LINUX_F_SEAL_EXEC	0x0020

#define	LINUX_MFD_CLOEXEC	0x0001
#define	LINUX_MFD_ALLOW_SEALING	0x0002
#define	LINUX_MFD_HUGETLB	0x0004

#define	LINUX_HUGETLB_FLAG_ENCODE_SHIFT	26
#define	LINUX_HUGETLB_FLAG_ENCODE_MASK	0x3f

#define LINUX_HUGETLB_FLAG_ENCODE_64KB	(16 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_512KB	(19 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_1MB	(20 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_2MB	(21 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_8MB	(23 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_16MB	(24 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_32MB	(25 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_256MB	(28 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_512MB	(29 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_1GB	(30 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_2GB	(31 << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)
#define LINUX_HUGETLB_FLAG_ENCODE_16GB	(34U << LINUX_HUGETLB_FLAG_ENCODE_SHIFT)

/* inotify flags */
#define	LINUX_IN_ACCESS		0x00000001
#define	LINUX_IN_MODIFY		0x00000002
#define	LINUX_IN_ATTRIB		0x00000004
#define	LINUX_IN_CLOSE_WRITE	0x00000008
#define	LINUX_IN_CLOSE_NOWRITE	0x00000010
#define	LINUX_IN_OPEN		0x00000020
#define	LINUX_IN_MOVED_FROM	0x00000040
#define	LINUX_IN_MOVED_TO	0x00000080
#define	LINUX_IN_CREATE		0x00000100
#define	LINUX_IN_DELETE		0x00000200
#define	LINUX_IN_DELETE_SELF	0x00000400
#define	LINUX_IN_MOVE_SELF	0x00000800

#define	LINUX_IN_UNMOUNT	0x00002000
#define	LINUX_IN_Q_OVERFLOW	0x00004000
#define	LINUX_IN_IGNORED	0x00008000

#define	LINUX_IN_ONLYDIR	0x01000000
#define	LINUX_IN_DONT_FOLLOW	0x02000000
#define	LINUX_IN_EXCL_UNLINK	0x04000000
#define	LINUX_IN_MASK_CREATE	0x10000000
#define	LINUX_IN_MASK_ADD	0x20000000
#define	LINUX_IN_ISDIR		0x40000000
#define	LINUX_IN_ONESHOT	0x80000000

#define	LINUX_IN_ALL_EVENTS	0x00000fff
#define	LINUX_IN_ALL_FLAGS	0xf700e000

#define	LINUX_IN_NONBLOCK	0x00000800
#define	LINUX_IN_CLOEXEC	0x00080000

#if defined(_KERNEL)
struct l_file_handle {
	l_uint handle_bytes;
	l_int handle_type;
	unsigned char f_handle[0];
};

int	linux_enobufs2eagain(struct thread *, int, int);
int	linux_common_openflags(int);
int	linux_kern_fadvise(struct thread *, int, off_t, off_t, int);
int	linux_kern_fallocate(struct thread *, int, int, off_t, off_t);
int	linux_kern_fallocate_fp(struct thread *, struct file *, int, off_t, off_t);
int	linux_kern_pipe2(struct thread *, int [2], int);
int	linux_kern_splice(struct thread *, int, off_t *, int, off_t *,
	    size_t, unsigned int);
#endif

/*
 * Look at linux_close_range() for an explanation.
 *
 * #define	LINUX_CLOSE_RANGE_UNSHARE	(1U << 1)
 */
#define	LINUX_CLOSE_RANGE_CLOEXEC	(1U << 2)

#endif	/* !_LINUX_FILE_H_ */
