/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only SMP wire oracles from Bluetooth Core 6.3 Vol 3 Part H:
 * §§3.5.1-3.5.5 and §3.5.8, including Tables 3.4, 3.5, and 3.7.
 * No production headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_SMP_DEEP_MISC_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_SMP_DEEP_MISC_ORACLES_H

#define BT_CORE63_SMP_PAIRING_REQUEST		0x01
#define BT_CORE63_SMP_PAIRING_RESPONSE		0x02
#define BT_CORE63_SMP_PAIRING_CONFIRM		0x03
#define BT_CORE63_SMP_PAIRING_RANDOM		0x04
#define BT_CORE63_SMP_PAIRING_FAILED		0x05
#define BT_CORE63_SMP_ENCRYPTION_INFORMATION	0x06
#define BT_CORE63_SMP_CENTRAL_IDENTIFICATION	0x07
#define BT_CORE63_SMP_IDENTITY_INFORMATION	0x08
#define BT_CORE63_SMP_IDENTITY_ADDRESS_INFO	0x09
#define BT_CORE63_SMP_SECURITY_REQUEST		0x0b
#define BT_CORE63_SMP_PAIRING_PUBLIC_KEY		0x0c
#define BT_CORE63_SMP_PAIRING_DHKEY_CHECK	0x0d
#define BT_CORE63_SMP_PAIRING_KEYPRESS_NOTIFY	0x0e

#define BT_CORE63_SMP_IO_DISPLAY_ONLY		0x00
#define BT_CORE63_SMP_IO_KEYBOARD_ONLY		0x02
#define BT_CORE63_SMP_IO_NO_INPUT_NO_OUTPUT	0x03

#define BT_CORE63_SMP_OOB_NOT_PRESENT		0x00
#define BT_CORE63_SMP_OOB_PRESENT		0x01
#define BT_CORE63_SMP_AUTH_BONDING		0x01
#define BT_CORE63_SMP_AUTH_MITM			0x04
#define BT_CORE63_SMP_AUTH_KEYPRESS		0x10
#define BT_CORE63_SMP_AUTH_SC			0x08
#define BT_CORE63_SMP_KEY_DIST_ENC_KEY		0x01
#define BT_CORE63_SMP_KEY_DIST_ID_KEY		0x02
#define BT_CORE63_SMP_KEY_DIST_NONE		0x00
#define BT_CORE63_SMP_F6_ADDR_PUBLIC		0x00
#define BT_CORE63_SMP_F6_ADDR_RANDOM		0x01
#define BT_CORE63_SMP_MAX_ENCRYPTION_KEY_SIZE	16
#define BT_CORE63_SMP_MIN_ENCRYPTION_KEY_SIZE	7
#define BT_CORE63_SMP_128_BIT_VALUE_SIZE		16

#define BT_CORE63_SMP_KEYPRESS_STARTED		0x00
#define BT_CORE63_SMP_KEYPRESS_DIGIT_ENTERED	0x01
#define BT_CORE63_SMP_KEYPRESS_DIGIT_ERASED	0x02
#define BT_CORE63_SMP_KEYPRESS_CLEARED		0x03
#define BT_CORE63_SMP_KEYPRESS_COMPLETED		0x04
#define BT_CORE63_SMP_KEYPRESS_TYPE_COUNT	5
/* First value outside the assigned §3.5.8 range, used as a negative input. */
#define BT_CORE63_SMP_KEYPRESS_FIRST_RESERVED	0x05

#define BT_CORE63_SMP_ERR_OOB_NOT_AVAILABLE	0x02
#define BT_CORE63_SMP_ERR_PAIRING_NOT_SUPPORTED	0x05
#define BT_CORE63_SMP_ERR_AUTH_REQUIREMENTS	0x03
#define BT_CORE63_SMP_ERR_CONFIRM_VALUE_FAILED	0x04
#define BT_CORE63_SMP_ERR_REPEATED_ATTEMPTS	0x09
#define BT_CORE63_SMP_ERR_UNSPECIFIED_REASON	0x08

#define BT_CORE63_SMP_PAIRING_FEATURE_PDU_SIZE	7
#define BT_CORE63_SMP_PAIRING_VALUE_PDU_SIZE	17
#define BT_CORE63_SMP_PAIRING_FAILED_PDU_SIZE	2
#define BT_CORE63_SMP_KEYPRESS_PDU_SIZE		2
#define BT_CORE63_SMP_SECURITY_REQUEST_PDU_SIZE	2
#define BT_CORE63_SMP_KEY_VALUE_PDU_SIZE		17
#define BT_CORE63_SMP_CENTRAL_ID_PDU_SIZE	11
#define BT_CORE63_SMP_ID_ADDR_PDU_SIZE		8
#define BT_CORE63_SMP_PUBLIC_KEY_PDU_SIZE	65

#endif /* TESTS_BLUETOOTH_SPEC_SMP_DEEP_MISC_ORACLES_H */
