#!/bin/sh
#
# Regenerate spec_conf_requirements_generated.tsv from the Bluetooth Core
# Specification text.  The output is a pure function of:
#
#   * bluetooth-specs/Core_Specification_6_3.txt
#   * spec_conf_extract_requirements.awk   (scope + normative-sentence rules)
#   * spec_conf_hci_scope.awk              (HCI scope derived from blued source)
#   * spec_conf_generation.awk             (feature -> Core version attribution)
#   * spec_conf_generation_map.tsv         (the curated recognising phrases)
#   * the NG_HCI_OCF_* symbols referenced by usr.sbin/bluetooth/blued
#
# so drift in any of them is visible as a diff.  This mirrors the contract of
# check_generated_oracles.sh for the oracle headers.
#
# Usage:
#   spec_conf_generate.sh              regenerate in place
#   spec_conf_generate.sh --check      fail if the checked-in file is stale
#   spec_conf_generate.sh -o FILE      write elsewhere

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
src_root=$(CDPATH= cd -- "$script_dir/../../../.." && pwd)
core="$src_root/bluetooth-specs/Core_Specification_6_3.txt"
blued="$src_root/usr.sbin/bluetooth/blued"
generated="$script_dir/spec_conf_requirements_generated.tsv"

# The Bluetooth generation this stack targets.  Requirements governing
# features introduced after it are classified NOT-APPLICABLE with the
# attributed generation as their reason; see docs/bluetooth-conformance.md.
target=5.2

mode=generate
out=""
while [ "$#" -gt 0 ]; do
	case "$1" in
	--check) mode=check; shift ;;
	-o) out=$2; shift 2 ;;
	-h|--help) sed -n '2,25p' "$0"; exit 0 ;;
	*) echo "usage: $0 [--check] [-o FILE]" >&2; exit 64 ;;
	esac
done
[ -n "$out" ] || out="$generated"

if [ ! -f "$core" ]; then
	echo "spec_conf: Core specification text absent: $core" >&2
	echo 'spec_conf: SIG source documents are local review inputs and are' >&2
	echo 'spec_conf: not redistributed; regeneration skipped.' >&2
	exit 66
fi
if [ ! -d "$blued" ]; then
	echo "spec_conf: blued sources absent: $blued" >&2
	exit 66
fi

tmpdir=$(mktemp -d -t bluetooth-specconf.XXXXXX)
trap 'rm -rf "$tmpdir"' EXIT HUP INT TERM

# 1. Scope HCI by the opcodes blued actually issues, not by all of Vol 4 Part E.
grep -rhoE 'NG_HCI_OCF_[A-Z0-9_]+' "$blued" | LC_ALL=C sort -u >"$tmpdir/ocf"
if [ ! -s "$tmpdir/ocf" ]; then
	echo 'spec_conf: no HCI opcodes found in blued' >&2
	exit 1
fi
hci_sections=$(awk -v OPCODES="$tmpdir/ocf" \
    -f "$script_dir/spec_conf_hci_scope.awk" "$core" 2>"$tmpdir/scope.err")
if [ -z "$hci_sections" ]; then
	echo 'spec_conf: HCI scope derivation produced no sections' >&2
	cat "$tmpdir/scope.err" >&2
	exit 1
fi

# 2. Extract the normative sentences for every in-scope Volume/Part.
{
	printf '# Generated by spec_conf_generate.sh; do not edit.\n'
	printf '# Source: Bluetooth Core Specification v6.3 (Core_Specification_6_3.txt)\n'
	printf '# HCI scope derived from %s NG_HCI_OCF_* symbols in blued.\n' \
	    "$(wc -l <"$tmpdir/ocf" | tr -d ' ')"
	printf 'requirement_id\tvolume_part\tsection\tkeyword\ttext\n'
	awk -v HCI_SECTIONS="$hci_sections" \
	    -f "$script_dir/spec_conf_extract_requirements.awk" "$core"
} >"$tmpdir/out"

# 3. Attribute each requirement to the Core version that introduced the
#    feature it governs, so post-target features can be scoped out with a
#    citation rather than by hand.
awk -v CORE="$core" -v MAP="$script_dir/spec_conf_generation_map.tsv" \
    -v TARGET="$target" -f "$script_dir/spec_conf_generation.awk" \
    "$tmpdir/out" >"$tmpdir/gen"

# 4. Classify coverage against the existing traceability matrix.
matrix="$script_dir/spec_requirements.tsv"
[ -f "$script_dir/spec_conf_requirements_proposed.tsv" ] &&
    matrix="$script_dir/spec_conf_requirements_proposed.tsv"
awk -v MATRIX="$matrix" -v GENMAP="$tmpdir/gen" -v TARGET="$target" \
    -f "$script_dir/spec_conf_coverage.awk" "$tmpdir/out" >"$tmpdir/cov"

# 5. Rank what is left.
awk -v REQS="$tmpdir/out" -f "$script_dir/spec_conf_rank.awk" "$tmpdir/cov" |
    { read -r hdr; printf '%s\n' "$hdr"; sort -t "$(printf '\t')" -k1,1nr \
	-k2,2; } >"$tmpdir/rank"

cov_out="$script_dir/spec_conf_coverage_generated.tsv"
rank_out="$script_dir/spec_conf_gaps_ranked.tsv"
gen_out="$script_dir/spec_conf_generation_generated.tsv"

# 6. Emit or compare.
if [ "$mode" = check ]; then
	rc=0
	for pair in "$tmpdir/out:$out" "$tmpdir/gen:$gen_out" \
	    "$tmpdir/cov:$cov_out" "$tmpdir/rank:$rank_out"; do
		cand=${pair%%:*}
		have=${pair#*:}
		if [ ! -f "$have" ]; then
			echo "spec_conf: $have is missing; run $0" >&2
			rc=1
			continue
		fi
		if ! cmp -s "$cand" "$have"; then
			echo "spec_conf: $have is stale; regenerate it" >&2
			diff -u "$have" "$cand" >&2 || true
			rc=1
		fi
	done
	[ "$rc" -eq 0 ] && echo 'spec_conf: generated catalogues are current'
	exit "$rc"
fi

cat "$tmpdir/out" >"$out"
cat "$tmpdir/gen" >"$gen_out"
cat "$tmpdir/cov" >"$cov_out"
cat "$tmpdir/rank" >"$rank_out"
sed -n '1,$p' "$tmpdir/scope.err" >&2
printf 'spec_conf: wrote %s normative requirements to %s\n' \
    "$(grep -vc '^#\|^requirement_id' "$out")" "$out"
awk -F'\t' 'NR > 1 { n[$4]++ } END { for (s in n) printf \
    "spec_conf: %-15s %d\n", s, n[s] }' "$cov_out"
awk -F'\t' 'NR > 1 { n[$4]++ } END { for (s in n) printf \
    "spec_conf: generation %-8s %d\n", s, n[s] }' "$gen_out" | sort
