/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only L2CAP wire oracles.  These values are transcribed from
 * Bluetooth Core 6.3 Vol 3 Part A §§2-6 and Assigned Numbers; this header
 * deliberately includes no kernel/netgraph Bluetooth headers.
 */
#ifndef TESTS_BLUETOOTH_SPEC_L2CAP_CORE63_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_L2CAP_CORE63_ORACLES_H

#include "spec_core63_generated.h"
#include "spec_assigned_generated.h"

/* Vol 3 Part A §2.1, Table 2.1. */
#define BT_CORE63_L2CAP_CID_SIGNAL		0x0001
#define BT_CORE63_L2CAP_CID_CONNECTIONLESS	0x0002
#define BT_CORE63_L2CAP_CID_ATT			0x0004
#define BT_CORE63_L2CAP_CID_LE_SIGNAL		0x0005
#define BT_CORE63_L2CAP_CID_SMP			0x0006
#define BT_CORE63_L2CAP_CID_DYNAMIC_FIRST	0x0040
#define BT_CORE63_L2CAP_CID_LE_DYNAMIC_LAST	0x007f

/* Vol 3 Part A §4, Table 4.1 and §§4.1-4.27. */
#define BT_CORE63_L2CAP_CMD_REJECT		0x01
#define BT_CORE63_L2CAP_CMD_CONNECTION_REQ	0x02
#define BT_CORE63_L2CAP_CMD_CONNECTION_RSP	0x03
#define BT_CORE63_L2CAP_CMD_CONFIG_REQ		0x04
#define BT_CORE63_L2CAP_CMD_CONFIG_RSP		0x05
#define BT_CORE63_L2CAP_CMD_DISCONNECT_REQ	0x06
#define BT_CORE63_L2CAP_CMD_DISCONNECT_RSP	0x07
#define BT_CORE63_L2CAP_CMD_ECHO_REQ		0x08
#define BT_CORE63_L2CAP_CMD_ECHO_RSP		0x09
#define BT_CORE63_L2CAP_CMD_INFO_REQ		0x0a
#define BT_CORE63_L2CAP_CMD_INFO_RSP		0x0b
#define BT_CORE63_L2CAP_CMD_PARAM_UPDATE_REQ	0x12
#define BT_CORE63_L2CAP_CMD_PARAM_UPDATE_RSP	0x13
#define BT_CORE63_L2CAP_CMD_LE_CREDIT_CONNECTION_REQ 0x14
#define BT_CORE63_L2CAP_CMD_LE_CREDIT_CONNECTION_RSP 0x15
#define BT_CORE63_L2CAP_CMD_FLOW_CONTROL_CREDIT	0x16
#define BT_CORE63_L2CAP_CMD_ECREDIT_CONNECTION_REQ 0x17
#define BT_CORE63_L2CAP_CMD_ECREDIT_CONNECTION_RSP 0x18
#define BT_CORE63_L2CAP_CMD_ECREDIT_RECONFIG_REQ	0x19
#define BT_CORE63_L2CAP_CMD_ECREDIT_RECONFIG_RSP	0x1a

/* Vol 3 Part A §4.1, Tables 4.3-4.4. */
#define BT_CORE63_L2CAP_REJECT_NOT_UNDERSTOOD	0x0000
#define BT_CORE63_L2CAP_REJECT_SIGNAL_MTU_EXCEEDED 0x0001
#define BT_CORE63_L2CAP_REJECT_INVALID_CID	0x0002

/* Vol 3 Part A §§4.3 and 4.5 response result tables. */
#define BT_CORE63_L2CAP_RESULT_SUCCESS		0x0000
#define BT_CORE63_L2CAP_RESULT_PENDING		0x0001
#define BT_CORE63_L2CAP_RESULT_PSM_NOT_SUPPORTED 0x0002
#define BT_CORE63_L2CAP_RESULT_SECURITY_BLOCK	0x0003
#define BT_CORE63_L2CAP_RESULT_NO_RESOURCES	0x0004
#define BT_CORE63_L2CAP_RESULT_INVALID_SOURCE_CID 0x0006
#define BT_CORE63_L2CAP_RESULT_SOURCE_CID_ALLOCATED 0x0007
#define BT_CORE63_L2CAP_CONFIG_UNACCEPTABLE_PARAMS 0x0001
#define BT_CORE63_L2CAP_CONFIG_REJECT		0x0002
#define BT_CORE63_L2CAP_CONFIG_UNKNOWN_OPTION	0x0003
#define BT_CORE63_L2CAP_CONFIG_PENDING		0x0004

/* Vol 3 Part A §§4.12-4.14. */
#define BT_CORE63_L2CAP_INFO_CONNECTIONLESS_MTU	0x0001
#define BT_CORE63_L2CAP_INFO_EXTENDED_FEATURES	0x0002
#define BT_CORE63_L2CAP_INFO_FIXED_CHANNELS	0x0003
#define BT_CORE63_L2CAP_INFO_NOT_SUPPORTED	0x0001

/* Vol 3 Part A §§4.22 and 4.25 result table. */
#define BT_CORE63_L2CAP_CREDIT_SUCCESS		0x0000
#define BT_CORE63_L2CAP_CREDIT_SPSM_NOT_SUPPORTED 0x0002
#define BT_CORE63_L2CAP_CREDIT_NO_RESOURCES	0x0004
#define BT_CORE63_L2CAP_CREDIT_INSUFF_AUTHENTICATION 0x0005
#define BT_CORE63_L2CAP_CREDIT_INSUFF_AUTHORIZATION 0x0006
#define BT_CORE63_L2CAP_CREDIT_INSUFF_KEY_SIZE	0x0007
#define BT_CORE63_L2CAP_CREDIT_INSUFF_ENCRYPTION 0x0008
#define BT_CORE63_L2CAP_CREDIT_INVALID_SOURCE_CID 0x0009
#define BT_CORE63_L2CAP_CREDIT_SOURCE_CID_ALLOCATED 0x000a
#define BT_CORE63_L2CAP_CREDIT_UNACCEPTABLE_PARAMS 0x000b
#define BT_CORE63_L2CAP_CREDIT_INVALID_PARAMS	0x000c

/* Vol 3 Part A §4.27, Table 4.20. */
#define BT_CORE63_L2CAP_RECONFIG_SUCCESS		0x0000
#define BT_CORE63_L2CAP_RECONFIG_MTU_REDUCTION	0x0001
#define BT_CORE63_L2CAP_RECONFIG_MPS_REDUCTION_MULTI 0x0002
#define BT_CORE63_L2CAP_RECONFIG_INVALID_DCID	0x0003
#define BT_CORE63_L2CAP_RECONFIG_UNACCEPTABLE_PARAMS 0x0004

/* Vol 3 Part A §§4.19-4.20. */
#define BT_CORE63_L2CAP_PARAM_UPDATE_ACCEPT	0x0000
#define BT_CORE63_L2CAP_PARAM_UPDATE_REJECT	0x0001

/* Vol 3 Part A §§5.1-5.3 and signaling option layouts. */
#define BT_CORE63_L2CAP_MTU_MIN_BR_EDR		48
#define BT_CORE63_L2CAP_MTU_DEFAULT_BR_EDR	672
#define BT_CORE63_L2CAP_MTU_MIN_ECREDIT		64
#define BT_CORE63_L2CAP_OPTION_CONTINUATION	0x0001
#define BT_CORE63_L2CAP_OPTION_HINT		0x80
#define BT_CORE63_L2CAP_OPTION_MTU		0x01
#define BT_CORE63_L2CAP_OPTION_FLUSH_TIMEOUT	0x02
#define BT_CORE63_L2CAP_OPTION_QOS		0x03
#define BT_CORE63_L2CAP_OPTION_QOS_VALUE_SIZE	22

/* Vol 3 Part A §10.1: a credit field is unsigned 16-bit. */
#define BT_CORE63_L2CAP_CREDIT_MAX		0xffff

/* Bluetooth SIG Assigned Numbers: fixed BR/EDR PSMs and EATT SPSM. */
#define BT_ASSIGNED_L2CAP_PSM_SDP		0x0001
#define BT_ASSIGNED_L2CAP_PSM_RFCOMM		0x0003
#define BT_ASSIGNED_L2CAP_PSM_TCS_BIN		0x0005
#define BT_ASSIGNED_L2CAP_SPSM_EATT		0x0027

/*
 * Tie the readable aliases above to the reproducibly generated Core/Assigned
 * namespaces.  check_generated_oracles.sh regenerates both included headers
 * from the local normative sources before the suite is accepted.
 */
#define BT_L2CAP_GENERATED_ENUM(name, value) BT_GENERATED_##name = (value),
enum {
	BT_CORE63_L2CAP_CID_ORACLES(BT_L2CAP_GENERATED_ENUM)
	BT_CORE63_L2CAP_COMMAND_ORACLES(BT_L2CAP_GENERATED_ENUM)
	BT_CORE63_L2CAP_RESULT_ORACLES(BT_L2CAP_GENERATED_ENUM)
	BT_CORE63_L2CAP_RECONFIG_RESULT_ORACLES(BT_L2CAP_GENERATED_ENUM)
	BT_ASSIGNED_EATT_PSM_ORACLES(BT_L2CAP_GENERATED_ENUM)
};
#undef BT_L2CAP_GENERATED_ENUM

_Static_assert(BT_CORE63_L2CAP_CID_SIGNAL ==
    BT_GENERATED_NG_L2CAP_SIGNAL_CID, "generated signaling CID");
_Static_assert(BT_CORE63_L2CAP_CID_CONNECTIONLESS ==
    BT_GENERATED_NG_L2CAP_CLT_CID, "generated connectionless CID");
_Static_assert(BT_CORE63_L2CAP_CID_ATT == BT_GENERATED_NG_L2CAP_ATT_CID,
    "generated ATT CID");
_Static_assert(BT_CORE63_L2CAP_CID_LE_SIGNAL ==
    BT_GENERATED_NG_L2CAP_LESIGNAL_CID, "generated LE signaling CID");
_Static_assert(BT_CORE63_L2CAP_CID_SMP == BT_GENERATED_NG_L2CAP_SMP_CID,
    "generated SMP CID");
_Static_assert(BT_CORE63_L2CAP_CID_DYNAMIC_FIRST ==
    BT_GENERATED_NG_L2CAP_FIRST_CID, "generated first dynamic CID");
_Static_assert(BT_CORE63_L2CAP_CID_LE_DYNAMIC_LAST ==
    BT_GENERATED_NG_L2CAP_LELAST_CID, "generated last LE dynamic CID");

_Static_assert(BT_CORE63_L2CAP_CMD_REJECT ==
    BT_GENERATED_NG_L2CAP_CMD_REJ, "generated command reject code");
_Static_assert(BT_CORE63_L2CAP_CMD_CONNECTION_REQ ==
    BT_GENERATED_NG_L2CAP_CON_REQ, "generated connection request code");
_Static_assert(BT_CORE63_L2CAP_CMD_CONNECTION_RSP ==
    BT_GENERATED_NG_L2CAP_CON_RSP, "generated connection response code");
_Static_assert(BT_CORE63_L2CAP_CMD_CONFIG_REQ ==
    BT_GENERATED_NG_L2CAP_CFG_REQ, "generated configuration request code");
_Static_assert(BT_CORE63_L2CAP_CMD_CONFIG_RSP ==
    BT_GENERATED_NG_L2CAP_CFG_RSP, "generated configuration response code");
_Static_assert(BT_CORE63_L2CAP_CMD_DISCONNECT_REQ ==
    BT_GENERATED_NG_L2CAP_DISCON_REQ, "generated disconnect request code");
_Static_assert(BT_CORE63_L2CAP_CMD_DISCONNECT_RSP ==
    BT_GENERATED_NG_L2CAP_DISCON_RSP, "generated disconnect response code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECHO_REQ ==
    BT_GENERATED_NG_L2CAP_ECHO_REQ, "generated echo request code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECHO_RSP ==
    BT_GENERATED_NG_L2CAP_ECHO_RSP, "generated echo response code");
_Static_assert(BT_CORE63_L2CAP_CMD_INFO_REQ ==
    BT_GENERATED_NG_L2CAP_INFO_REQ, "generated information request code");
_Static_assert(BT_CORE63_L2CAP_CMD_INFO_RSP ==
    BT_GENERATED_NG_L2CAP_INFO_RSP, "generated information response code");
_Static_assert(BT_CORE63_L2CAP_CMD_PARAM_UPDATE_REQ ==
    BT_GENERATED_NG_L2CAP_CMD_PARAM_UPDATE_REQUEST,
    "generated parameter update request code");
_Static_assert(BT_CORE63_L2CAP_CMD_PARAM_UPDATE_RSP ==
    BT_GENERATED_NG_L2CAP_CMD_PARAM_UPDATE_RESPONSE,
    "generated parameter update response code");
_Static_assert(BT_CORE63_L2CAP_CMD_LE_CREDIT_CONNECTION_REQ ==
    BT_GENERATED_NG_L2CAP_LE_CREDIT_CON_REQ,
    "generated LE credit connection request code");
_Static_assert(BT_CORE63_L2CAP_CMD_LE_CREDIT_CONNECTION_RSP ==
    BT_GENERATED_NG_L2CAP_LE_CREDIT_CON_RSP,
    "generated LE credit connection response code");
_Static_assert(BT_CORE63_L2CAP_CMD_FLOW_CONTROL_CREDIT ==
    BT_GENERATED_NG_L2CAP_FLOW_CONTROL_CREDIT,
    "generated flow control credit code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECREDIT_CONNECTION_REQ ==
    BT_GENERATED_NG_L2CAP_CREDIT_CON_REQ,
    "generated enhanced credit connection request code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECREDIT_CONNECTION_RSP ==
    BT_GENERATED_NG_L2CAP_CREDIT_CON_RSP,
    "generated enhanced credit connection response code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECREDIT_RECONFIG_REQ ==
    BT_GENERATED_NG_L2CAP_CREDIT_RECONFIG_REQ,
    "generated enhanced credit reconfigure request code");
_Static_assert(BT_CORE63_L2CAP_CMD_ECREDIT_RECONFIG_RSP ==
    BT_GENERATED_NG_L2CAP_CREDIT_RECONFIG_RSP,
    "generated enhanced credit reconfigure response code");

_Static_assert(BT_CORE63_L2CAP_CREDIT_SUCCESS ==
    BT_GENERATED_NG_L2CAP_LE_COC_SUCCESS, "generated credit success");
_Static_assert(BT_CORE63_L2CAP_CREDIT_SPSM_NOT_SUPPORTED ==
    BT_GENERATED_NG_L2CAP_LE_COC_SPSM_NOT_SUPPORTED,
    "generated SPSM-not-supported result");
_Static_assert(BT_CORE63_L2CAP_CREDIT_NO_RESOURCES ==
    BT_GENERATED_NG_L2CAP_LE_COC_NO_RESOURCES,
    "generated no-resources result");
_Static_assert(BT_CORE63_L2CAP_CREDIT_INSUFF_ENCRYPTION ==
    BT_GENERATED_NG_L2CAP_LE_COC_INSUFF_ENC,
    "generated insufficient-encryption result");
_Static_assert(BT_CORE63_L2CAP_CREDIT_INVALID_SOURCE_CID ==
    BT_GENERATED_NG_L2CAP_LE_COC_INVALID_SCID,
    "generated invalid-source-CID result");
_Static_assert(BT_CORE63_L2CAP_CREDIT_SOURCE_CID_ALLOCATED ==
    BT_GENERATED_NG_L2CAP_LE_COC_SCID_IN_USE,
    "generated source-CID-allocated result");
_Static_assert(BT_CORE63_L2CAP_CREDIT_UNACCEPTABLE_PARAMS ==
    BT_GENERATED_NG_L2CAP_LE_COC_UNACCEPTABLE_PARAMS,
    "generated unacceptable-parameters result");

_Static_assert(BT_CORE63_L2CAP_RECONFIG_SUCCESS ==
    BT_GENERATED_NG_L2CAP_RECONFIG_SUCCESS, "generated reconfig success");
_Static_assert(BT_CORE63_L2CAP_RECONFIG_MTU_REDUCTION ==
    BT_GENERATED_NG_L2CAP_RECONFIG_MTU_REDUCTION,
    "generated MTU-reduction result");
_Static_assert(BT_CORE63_L2CAP_RECONFIG_MPS_REDUCTION_MULTI ==
    BT_GENERATED_NG_L2CAP_RECONFIG_MPS_REDUCTION_MULTI,
    "generated MPS-reduction result");
_Static_assert(BT_CORE63_L2CAP_RECONFIG_INVALID_DCID ==
    BT_GENERATED_NG_L2CAP_RECONFIG_INVALID_DCID,
    "generated invalid-DCID result");
_Static_assert(BT_CORE63_L2CAP_RECONFIG_UNACCEPTABLE_PARAMS ==
    BT_GENERATED_NG_L2CAP_RECONFIG_UNACCEPTABLE_PARAMS,
    "generated reconfiguration parameters result");
_Static_assert(BT_ASSIGNED_L2CAP_SPSM_EATT ==
    BT_GENERATED_NG_L2CAP_PSM_EATT, "generated Assigned Numbers EATT SPSM");

#endif /* TESTS_BLUETOOTH_SPEC_L2CAP_CORE63_ORACLES_H */
