/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Core 6.3 byte assignments for hci_emulator_test.
 * No production or Netgraph Bluetooth header is included.
 */

#ifndef TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ORACLES_H

#include "spec_hci_emulator_link_oracles.h"

/* Core 6.3 Vol 4 Part A §2, Table 2.1. */
#define HCI_EMU_SPEC_CMD_PKT	HCI_LINK_SPEC_CMD_PKT
#define HCI_EMU_SPEC_EVENT_PKT	HCI_LINK_SPEC_NG_HCI_EVENT_PKT

/* Core 6.3 Vol 4 Part E §§7.3.1, 7.3.2, 7.3.79. */
#define HCI_EMU_SPEC_OP_SET_EVENT_MASK		0x0c01
#define HCI_EMU_SPEC_OP_RESET			0x0c03
#define HCI_EMU_SPEC_OP_WRITE_LE_HOST_SUPPORTED	0x0c6d

/* Core 6.3 Vol 4 Part E §§7.4.1-7.4.6. */
#define HCI_EMU_SPEC_OP_READ_LOCAL_VERSION	0x1001
#define HCI_EMU_SPEC_OP_READ_LOCAL_COMMANDS	0x1002
#define HCI_EMU_SPEC_OP_READ_LOCAL_FEATURES	0x1003
#define HCI_EMU_SPEC_OP_READ_BUFFER_SIZE	0x1005
#define HCI_EMU_SPEC_OP_READ_BD_ADDR		0x1009

/* Core 6.3 Vol 4 Part E §§7.8.1-7.8.11, 7.8.38, 7.8.44. */
#define HCI_EMU_SPEC_OP_LE_SET_EVENT_MASK	0x2001
#define HCI_EMU_SPEC_OP_LE_READ_BUFFER_SIZE	0x2002
#define HCI_EMU_SPEC_OP_LE_READ_LOCAL_FEATURES	0x2003
#define HCI_EMU_SPEC_OP_LE_SET_RANDOM_ADDRESS	0x2005
#define HCI_EMU_SPEC_OP_LE_SET_ADV_PARAMS	0x2006
#define HCI_EMU_SPEC_OP_LE_SET_ADV_DATA		0x2008
#define HCI_EMU_SPEC_OP_LE_SET_SCAN_RSP_DATA	0x2009
#define HCI_EMU_SPEC_OP_LE_SET_ADV_ENABLE	0x200a
#define HCI_EMU_SPEC_OP_LE_SET_SCAN_PARAMS	0x200b
#define HCI_EMU_SPEC_OP_LE_SET_SCAN_ENABLE	0x200c
#define HCI_EMU_SPEC_OP_LE_ADD_RESOLVING_LIST	0x2027
#define HCI_EMU_SPEC_OP_LE_SET_ADDR_RES_ENABLE	0x202d

/* Core 6.3 Vol 4 Part E §§7.8.2, 7.8.58, 7.8.61, 7.8.63, 7.8.88-7.8.89. */
#define HCI_EMU_SPEC_OP_LE_READ_NUM_ADV_SETS	0x203b
#define HCI_EMU_SPEC_OP_LE_SET_PERIODIC_ADV_PARAMS	0x203e
#define HCI_EMU_SPEC_OP_LE_SET_PERIODIC_ADV_ENABLE	0x2040
#define HCI_EMU_SPEC_OP_LE_SET_PERIODIC_ADV_RCV_ENABLE	0x2059
#define HCI_EMU_SPEC_OP_LE_PERIODIC_ADV_SYNC_TRANSFER	0x205a
#define HCI_EMU_SPEC_OP_LE_READ_BUFFER_SIZE_V2	0x2060
#define HCI_EMU_SPEC_UNKNOWN_VENDOR_OPCODE	0xffff

/* Core 6.3 Vol 4 Part E §§7.7.5, 7.7.14, and 7.7.65. */
#define HCI_EMU_SPEC_EVENT_DISCON_COMPLETE \
	HCI_LINK_SPEC_NG_HCI_EVENT_DISCON_COMPL
#define HCI_EMU_SPEC_EVENT_COMMAND_COMPLETE \
	HCI_LINK_SPEC_NG_HCI_EVENT_COMMAND_COMPL
#define HCI_EMU_SPEC_EVENT_LE_META	HCI_LINK_SPEC_NG_HCI_EVENT_LE
#define HCI_EMU_SPEC_SUBEVENT_LE_CONN_COMPLETE \
	HCI_LINK_SPEC_NG_HCI_LEEV_CON_COMPL
#define HCI_EMU_SPEC_SUBEVENT_LE_ADV_REPORT \
	HCI_LINK_SPEC_NG_HCI_LEEV_ADVREP
#define HCI_EMU_SPEC_SUBEVENT_PERIODIC_SYNC_ESTABLISHED	0x0e
#define HCI_EMU_SPEC_SUBEVENT_PERIODIC_ADV_REPORT	0x0f
#define HCI_EMU_SPEC_SUBEVENT_PERIODIC_SYNC_LOST	0x10

/* Core 6.3 Vol 1 Part F §1.3, Table 1.1. */
#define HCI_EMU_SPEC_STATUS_SUCCESS		0x00
#define HCI_EMU_SPEC_ERR_UNKNOWN_HCI_COMMAND	0x01
#define HCI_EMU_SPEC_ERR_COMMAND_DISALLOWED	0x0c
#define HCI_EMU_SPEC_REASON_REMOTE_USER_TERM	0x13

/* Exact fixed event/command-return field sizes from the cited command tables. */
#define HCI_EMU_SPEC_CC_FIXED_PARAM_LEN	3
#define HCI_EMU_SPEC_CC_TYPED_HEADER_LEN	6
#define HCI_EMU_SPEC_CONN_COMPLETE_PARAM_LEN	19
#define HCI_EMU_SPEC_DISCON_COMPLETE_PARAM_LEN	4
#define HCI_EMU_SPEC_NUM_COMMAND_PACKETS	1
#define HCI_EMU_SPEC_ADV_REPORT_FIXED_PARAM_LEN	12
#define HCI_EMU_SPEC_PERIODIC_SYNC_EST_PARAM_LEN	16
#define HCI_EMU_SPEC_PERIODIC_REPORT_FIXED_PARAM_LEN	8
#define HCI_EMU_SPEC_PERIODIC_SYNC_LOST_PARAM_LEN	3

/* Core 6.3 command parameter assignments. */
#define HCI_EMU_SPEC_DISABLED		0x00
#define HCI_EMU_SPEC_ENABLED		0x01
#define HCI_EMU_SPEC_ADDR_PUBLIC	0x00
#define HCI_EMU_SPEC_ADDR_RANDOM	0x01
#define HCI_EMU_SPEC_ROLE_PERIPHERAL	0x01
#define HCI_EMU_SPEC_ADV_IND		0x00

#endif /* TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ORACLES_H */
