# Produce a proposed replacement for spec_requirements.tsv that stops counting
# implementation contracts as specification conformance.
#
# The existing file has four columns and no way to say "this row is a contract
# about our own source, not a normative requirement".  spec_traceability_audit.sh
# therefore reports 317/317 requirements covered, which reads as 317 conformance
# requirements when roughly a sixth of them cite only our own .c files.
#
# The proposal keeps the first four columns byte-identical and appends three
# machine-checkable classification columns:
#
#   authority       normative | implementation | mixed
#                   Derived from exact_reference: does it cite a published
#                   specification, our own source tree, or both?
#   oracle_class    external | internal | mixed
#                   Does the oracle column claim an origin outside the
#                   implementation (spec-extracted constant, published vector,
#                   independently constructed bytes) or not?
#   spec_source     in-tree | absent:<documents> | n/a
#                   Is the cited document present under bluetooth-specs, so the
#                   oracle can be drift-checked at all?
#
# Only rows with authority=normative AND spec_source=in-tree may be counted as
# specification conformance.

BEGIN {
	FS = "\t"
	OFS = "\t"
	printf "# Proposed replacement for spec_requirements.tsv.\n"
	printf "# Generated by spec_conf_relabel.awk; see docs/bluetooth-conformance.md.\n"
	printf "# Columns 1-4 are unchanged; 5-7 classify the row.\n"
	printf "requirement_id\texact_reference\tkyua_selector\toracle\tauthority\toracle_class\tspec_source\n"
}

/^#/ { next }
$1 == "requirement_id" { next }
NF < 4 { next }

{
	ref = $2
	oracle = $4

	spec = (ref ~ /Bluetooth Core|Core Specification|GATT Specification Supplement|Assigned Numbers|CSS v|Mesh Protocol|Mesh Model|Mesh Remote|HID Over GATT|HID over GATT|HID Service|A2DP|AVDTP|AVRCP|Common Audio Profile|NIST|FIPS|RFC |IEEE Std/)
	impl = (ref ~ /usr\.sbin\/bluetooth|tests\/usr\.sbin|lib\/libble|lib\/libmesh|sys\/netgraph|Implementation contract/)

	if (spec && impl)
		authority = "mixed"
	else if (spec)
		authority = "normative"
	else
		authority = "implementation"

	ext = (oracle ~ /[Ii]ndependent|[Pp]ublished|[Gg]enerated|NIST|FIPS|RFC|AESAVS|known-answer|KAT|Appendix|sample data|test vector|vectors|[Ee]xternal|Core-defined/)
	int_only = (oracle ~ /implementation policy|local API|local contract|not claimed|does not claim|private-contract|[Ll]ocal /)
	if (ext && int_only)
		oracle_class = "mixed"
	else if (ext)
		oracle_class = "external"
	else
		oracle_class = "internal"

	# Which cited documents actually exist under bluetooth-specs?
	#
	# Present: Core_Specification_6_3, Assigned_Numbers,
	#          GATT_Specification_Supplement, MshPRT_v1.1.1, MshMDL_v1.1.1,
	#          Device_Properties, CSS_v15, HOGP_v1.1, HOGP_v1.2, HIDS_v1.1,
	#          A2DP, AVDTP, AVRCP, CAP.
	# Absent:  the four GATT service specifications cited by the
	#          hogp_scenario_test rows.  Their characteristics are defined in
	#          the GATT Specification Supplement, which is present, but the
	#          service documents that fix the mandatory-characteristic sets
	#          and the service-level behaviour are not held here, so those
	#          oracles cannot be drift-checked against a normative source.
	#
	# "Mesh Remote Provisioning" is not a separate SIG deliverable; it is
	# Mesh Protocol 1.1.1 Section 4, so a row citing it is satisfied by
	# MshPRT_v1.1.1.
	#
	# This list is static so that regenerating the matrix does not depend on
	# having the documents to hand.  It cannot rot silently: the ATF case
	# spec_conf_traceability_test:cited_documents_are_accounted_for checks
	# every row of the result against the actual contents of
	# bluetooth-specs, in both directions.
	missing = ""
	if (ref ~ /Battery Service/)
		missing = missing "Battery Service;"
	if (ref ~ /Device Information Service/)
		missing = missing "Device Information Service;"
	if (ref ~ /Heart Rate Service/)
		missing = missing "Heart Rate Service;"
	if (ref ~ /Health Thermometer Service/)
		missing = missing "Health Thermometer Service;"

	if (authority == "implementation")
		spec_source = "n/a"
	else if (missing != "") {
		sub(/;$/, "", missing)
		spec_source = "absent:" missing
	} else
		spec_source = "in-tree"

	print $1, $2, $3, $4, authority, oracle_class, spec_source
}
