/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only HCI encryption, timeout, and power-control oracles from Bluetooth
 * Core 6.3 Vol 4 Part E §§7.7.5, 7.7.8, 7.7.15, 7.7.65.5,
 * 7.7.65.32-7.7.65.33, 7.8.24-7.8.26, and 7.8.118-7.8.120.
 * No production or Netgraph headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ENC_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ENC_ORACLES_H

#define BT_CORE63_HCI_OP_LE_ENABLE_ENCRYPTION	0x2019
#define BT_CORE63_HCI_COMMAND_PACKET		0x01
#define BT_CORE63_HCI_OP_LE_LTK_REQ_REPLY	0x201a
#define BT_CORE63_HCI_OP_LE_LTK_REQ_NEG_REPLY	0x201b
#define BT_CORE63_HCI_OP_LE_READ_REMOTE_TX_POWER	0x2077
#define BT_CORE63_HCI_OP_LE_SET_PATH_LOSS_PARAMS	0x2078
#define BT_CORE63_HCI_OP_LE_SET_PATH_LOSS_ENABLE	0x2079

#define BT_CORE63_HCI_EVENT_PACKET		0x04
#define BT_CORE63_HCI_EVENT_DISCON_COMPLETE	0x05
#define BT_CORE63_HCI_EVENT_ENCRYPTION_CHANGE	0x08
#define BT_CORE63_HCI_EVENT_COMMAND_COMPLETE	0x0e
#define BT_CORE63_HCI_EVENT_COMMAND_STATUS	0x0f
#define BT_CORE63_HCI_EVENT_LE_META		0x3e
#define BT_CORE63_HCI_LE_SUBEVENT_LTK_REQUEST	0x05
#define BT_CORE63_HCI_LE_SUBEVENT_PATH_LOSS	0x20
#define BT_CORE63_HCI_LE_SUBEVENT_TX_POWER	0x21

#define BT_CORE63_HCI_STATUS_SUCCESS		0x00
#define BT_CORE63_HCI_ERR_PIN_OR_KEY_MISSING	0x06
#define BT_CORE63_HCI_ERR_CONNECTION_TIMEOUT	0x08
#define BT_CORE63_HCI_ENCRYPTION_DISABLED	0x00
#define BT_CORE63_HCI_ENCRYPTION_AES_CCM		0x01
#define BT_CORE63_HCI_PHY_LE_1M			0x01
#define BT_CORE63_HCI_TX_POWER_REASON_READ_COMPLETE 0x02
#define BT_CORE63_HCI_TX_POWER_FLAG_NEITHER	0x00
#define BT_CORE63_HCI_PATH_LOSS_ZONE_MIDDLE	0x01

#define BT_CORE63_HCI_ENC_CHANGE_PARAM_SIZE	4
#define BT_CORE63_HCI_LTK_REQUEST_PARAM_SIZE	13
#define BT_CORE63_HCI_COMMAND_COMPLETE_HANDLE_PARAM_SIZE 6
#define BT_CORE63_HCI_TX_POWER_REPORT_PARAM_SIZE	9
#define BT_CORE63_HCI_PATH_LOSS_REPORT_PARAM_SIZE 5
#define BT_CORE63_HCI_LE_ENABLE_ENCRYPTION_PARAM_SIZE 28
#define BT_CORE63_HCI_LE_LTK_REPLY_PARAM_SIZE	18
#define BT_CORE63_HCI_LE_LTK_NEG_REPLY_PARAM_SIZE 2
#define BT_CORE63_HCI_LE_READ_TX_POWER_PARAM_SIZE 3
#define BT_CORE63_HCI_LE_PATH_LOSS_PARAMS_SIZE	8
#define BT_CORE63_HCI_LE_PATH_LOSS_ENABLE_SIZE	3

#endif /* TESTS_BLUETOOTH_SPEC_HCI_EMULATOR_ENC_ORACLES_H */
