/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Mesh Remote Provisioning 1.1 wire assignments.
 * No production Mesh header is included.
 */

#ifndef TESTS_BLUETOOTH_SPEC_MESH_REMOTE_PROV_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_MESH_REMOTE_PROV_ORACLES_H

/* Mesh Model 1.1.1 §4.4.4 message opcodes. */
#define BT_RP_SPEC_OP_SCAN_CAPS_GET		0x804f
#define BT_RP_SPEC_OP_SCAN_CAPS_STATUS		0x8050
#define BT_RP_SPEC_OP_SCAN_GET			0x8051
#define BT_RP_SPEC_OP_SCAN_START		0x8052
#define BT_RP_SPEC_OP_SCAN_STOP			0x8053
#define BT_RP_SPEC_OP_SCAN_STATUS		0x8054
#define BT_RP_SPEC_OP_SCAN_REPORT		0x8055
#define BT_RP_SPEC_OP_EXT_SCAN_START		0x8056
#define BT_RP_SPEC_OP_EXT_SCAN_REPORT		0x8057
#define BT_RP_SPEC_OP_LINK_GET			0x8058
#define BT_RP_SPEC_OP_LINK_OPEN			0x8059
#define BT_RP_SPEC_OP_LINK_CLOSE		0x805a
#define BT_RP_SPEC_OP_LINK_STATUS		0x805b
#define BT_RP_SPEC_OP_LINK_REPORT		0x805c
#define BT_RP_SPEC_OP_PDU_SEND			0x805d
#define BT_RP_SPEC_OP_PDU_OUTBOUND_REPORT	0x805e
#define BT_RP_SPEC_OP_PDU_REPORT		0x805f

/* Mesh Model 1.1.1 §4.4.4 Remote Provisioning status/state values. */
#define BT_RP_SPEC_STATUS_SUCCESS		0x00
#define BT_RP_SPEC_STATUS_SCAN_CANNOT_START	0x01
#define BT_RP_SPEC_STATUS_INVALID_STATE		0x02
#define BT_RP_SPEC_STATUS_LINK_CLOSED_BY_DEVICE	0x06
#define BT_RP_SPEC_STATUS_LINK_CLOSED_BY_SERVER	0x07
#define BT_RP_SPEC_STATUS_CANNOT_TX_PDU		0x0a
#define BT_RP_SPEC_SCAN_IDLE			0x00
#define BT_RP_SPEC_SCAN_ACTIVE			0x01
#define BT_RP_SPEC_SCAN_LIMITED			0x02
#define BT_RP_SPEC_LINK_IDLE			0x00
#define BT_RP_SPEC_LINK_OPENING			0x01
#define BT_RP_SPEC_LINK_ACTIVE			0x02
#define BT_RP_SPEC_LINK_OUTBOUND_TRANSFER	0x03
#define BT_RP_SPEC_LINK_CLOSING			0x04
#define BT_RP_SPEC_LINK_CLOSE_SUCCESS		0x00
#define BT_RP_SPEC_LINK_CLOSE_PROHIBITED	0x01
#define BT_RP_SPEC_LINK_CLOSE_FAIL		0x02
#define BT_RP_SPEC_NPPI_DEVICE_KEY_REFRESH	0x00
#define BT_RP_SPEC_NPPI_NODE_ADDRESS_REFRESH	0x01
#define BT_RP_SPEC_NPPI_NODE_COMPOSITION_REFRESH 0x02

/* Mesh Model 1.1.1 Scan Capabilities/Link Open field constraints. */
#define BT_RP_SPEC_SCAN_CAPS_MIN_ITEMS		0x04
#define BT_RP_SPEC_ACTIVE_SCAN_SUPPORTED	0x01
#define BT_RP_SPEC_LINK_TIMEOUT_MAX		0x3c

/* Mesh Protocol 1.1 §5.4.1 Provisioning PDU types and algorithms. */
#define BT_RP_SPEC_PROV_INVITE			0x00
#define BT_RP_SPEC_PROV_CAPABILITIES		0x01
#define BT_RP_SPEC_ALGO_BIT_P256_CMAC		0x0001

/* Mesh Model 1.1.1 Table 4.176 permitted Extended Scan AD filters. */
#define BT_RP_SPEC_AD_UUID16_COMPLETE		0x03
#define BT_RP_SPEC_AD_UUID16_INCOMPLETE		0x02
#define BT_RP_SPEC_AD_UUID32_COMPLETE		0x05
#define BT_RP_SPEC_AD_UUID32_INCOMPLETE		0x04
#define BT_RP_SPEC_AD_UUID128_COMPLETE		0x07
#define BT_RP_SPEC_AD_UUID128_INCOMPLETE	0x06
#define BT_RP_SPEC_AD_NAME_SHORT		0x08
#define BT_RP_SPEC_AD_NAME_COMPLETE		0x09
#define BT_RP_SPEC_AD_URI			0x24

#endif /* TESTS_BLUETOOTH_SPEC_MESH_REMOTE_PROV_ORACLES_H */
