/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Independent Bluetooth Core 6.3 LE SMP Secure Connections assignments.
 * No production SMP header is included.
 */

#ifndef TESTS_BLUETOOTH_SPEC_SMP_SC_EDGE_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_SMP_SC_EDGE_ORACLES_H

/* Core 6.3 Vol 3 Part H §3.3 Table 3.1: SMP command codes. */
#define BT_SC_SPEC_PAIRING_REQUEST		0x01
#define BT_SC_SPEC_PAIRING_RESPONSE		0x02
#define BT_SC_SPEC_PAIRING_CONFIRM		0x03
#define BT_SC_SPEC_PAIRING_RANDOM		0x04
#define BT_SC_SPEC_PAIRING_FAILED		0x05
#define BT_SC_SPEC_PAIRING_PUBLIC_KEY		0x0c
#define BT_SC_SPEC_PAIRING_DHKEY_CHECK		0x0d

/* Core 6.3 Vol 3 Part H §3.5.5 Table 3.7: Pairing Failed reasons. */
#define BT_SC_SPEC_ERR_PASSKEY_ENTRY_FAILED	0x01
#define BT_SC_SPEC_ERR_OOB_NOT_AVAILABLE	0x02
#define BT_SC_SPEC_ERR_CONFIRM_VALUE_FAILED	0x04
#define BT_SC_SPEC_ERR_PAIRING_NOT_SUPPORTED	0x05
#define BT_SC_SPEC_ERR_UNSPECIFIED_REASON	0x08
#define BT_SC_SPEC_ERR_DHKEY_CHECK_FAILED	0x0b
#define BT_SC_SPEC_ERR_NUMERIC_COMP_FAILED	0x0c

/* Core 6.3 Vol 3 Part H §§2.3.2, 3.5.1: Pairing feature fields. */
#define BT_SC_SPEC_IO_DISPLAY_ONLY		0x00
#define BT_SC_SPEC_IO_DISPLAY_YESNO		0x01
#define BT_SC_SPEC_IO_KEYBOARD_ONLY		0x02
#define BT_SC_SPEC_IO_NO_INPUT_NO_OUTPUT	0x03
#define BT_SC_SPEC_IO_KEYBOARD_DISPLAY		0x04
#define BT_SC_SPEC_AUTH_BONDING			0x01
#define BT_SC_SPEC_AUTH_MITM			0x04
#define BT_SC_SPEC_AUTH_SECURE_CONNECTIONS	0x08
#define BT_SC_SPEC_KEY_DIST_ID_KEY		0x02
#define BT_SC_SPEC_MAX_ENCRYPTION_KEY_SIZE	16

#define BT_SC_SPEC_PAIRING_FEATURE_PDU_LEN	7
#define BT_SC_SPEC_FAILED_PDU_LEN		2
#define BT_SC_SPEC_128_BIT_PDU_LEN		17
#define BT_SC_SPEC_PUBLIC_KEY_PDU_LEN		65

#endif /* TESTS_BLUETOOTH_SPEC_SMP_SC_EDGE_ORACLES_H */
