/*
 * EXTERNAL REFERENCE ORACLE: the HCI LE Event Mask -- bit assignments, the
 * specified default, the "Controller shall ignore unsupported bits" rule, and
 * the three reference stacks' gating strategies.
 *
 * Hand-written.  Every value and every claim below is traceable to a named
 * external source; nothing here was derived from blued, and no value was
 * produced by running 5BSD code.
 *
 * WHY THIS HEADER EXISTS
 * ----------------------
 * blued builds its LE event mask by hand in hci_le_default_event_mask() and
 * gates individual bits on LE FEATURE bits.  Two things make that error-prone,
 * and both are recorded here so a test can pin them:
 *
 *   1. The mask bit numbering and the LE feature bit numbering are DIFFERENT
 *      numbering spaces.  A bit gated on the wrong feature is silently lost:
 *      the command still succeeds, and the event simply never arrives.
 *
 *   2. Gating is not required at all.  Section 7.8.1 obliges the Controller to
 *      ignore bits it does not support, so an ungated mask is legal and safe.
 *      Gating can therefore only LOSE events; it can never protect the host.
 *      This is the asymmetry that makes a wrong gate a one-way failure.
 *
 * A masked event is not merely "not delivered".  For bit 5 the Link Layer is
 * required to REJECT the peer's procedure on the air -- see
 * BT_EXTREF_LE_EVTMASK_BIT5_MASKED_LL_REJECT_ERROR below.
 *
 * SPEC
 * ----
 * /usr/src/bluetooth-specs/Core_Specification_6_3.txt
 *
 *   Vol 4, Part E, Section 7.8.1 "LE Set Event Mask command"
 *   (text lines 111760-111800 and the bit table at 111800-111860).
 *
 *   Description, verbatim (text lines 111768-111780):
 *     "This command is used to control which LE events are generated by the
 *      HCI for the Host. If the bit in the LE_Event_Mask is set to a one, then
 *      the event associated with that bit will be enabled."
 *     "The Controller shall ignore those bits which are reserved for future
 *      use or represent events which it does not support. If the Host sets any
 *      of these bits to 1, the Controller shall act as if they were set to 0."
 *     "For LE events to be generated, the LE Meta event bit in the Event_Mask
 *      shall also be set. If that bit is not set, then LE events shall not be
 *      generated, regardless of how the LE_Event_Mask is set."
 *
 *   Default, verbatim (text line ~111857):
 *     "The value with all bits set to 0 indicates that no events are
 *      specified. The default is for just bits 0 to 4 to be set."
 *
 *   Vol 6, Part B, Section 5.1.7.2 "Responding to LL_CONNECTION_PARAM_REQ and
 *   LL_CONNECTION_PARAM_RSP PDUs" (text lines 143896-143901), verbatim:
 *     "If the request is being indicated to the Host and the event to the Host
 *      is masked, then the Link Layer shall issue an LL_REJECT_EXT_IND PDU
 *      with the ErrorCode set to Unsupported Remote Feature (0x1A). The
 *      initiating device may retry in case this is a temporary situation. If
 *      the request is not being indicated to the Host, then the event mask
 *      shall be ignored."
 *
 *   Vol 4, Part E, Section 7.7.65.25 "LE CIS Established event" (text lines
 *   107560-107564), verbatim:
 *     "This event indicates that a CIS has been established, was considered
 *      lost before being established, or--on the Central--was rejected by the
 *      Peripheral. It is generated by the Controller in the Central and
 *      Peripheral."
 *   -- i.e. this event is NOT central-only, so gating its mask bit on a
 *   central-only feature bit loses it on a peripheral.
 *
 * REFERENCE IMPLEMENTATIONS
 * -------------------------
 *   Apache NimBLE, github.com/apache/mynewt-nimble, snapshot commit
 *   1e8ed60276f35a80ed4d4b4f8bb9d9c6fee53845:
 *     nimble/host/src/ble_hs_startup.c:212-330 -- gates the mask on the HCI
 *     VERSION read by ble_hs_startup_read_local_ver_tx()
 *     (ble_hs_startup.c:53, called at :411), not on feature bits.  Bit 5 is
 *     set for any controller reporting >= 4.1 (:220-225); bits 10 and 19 are
 *     set at >= 4.2 and >= 5.0 respectively (:227-235, :237-251).
 *
 *   Zephyr, github.com/zephyrproject-rtos/zephyr, snapshot commit
 *   2665fcca3cced3aefb7202d6289991d8cc1dfcac:
 *     subsys/bluetooth/host/hci_core.c:3765-3766 -- sets bit 5 gated on the LE
 *     feature bit for the Connection Parameters Request Procedure:
 *         if (BT_FEAT_LE_CONN_PARAM_REQ_PROC(bt_dev.le.features)) {
 *                 mask |= BT_EVT_MASK_LE_CONN_PARAM_REQ;
 *     include/zephyr/bluetooth/hci_types.h:4584 defines that mask as
 *     BT_EVT_BIT(5); :163 and :221-222 define the FEATURE bit as 1.  The two
 *     numbers differ, which is precisely the trap this header records.
 *     Zephyr also implements the event (hci_core.c:3075) and both replies
 *     (hci_core.c:2082, :2105).
 *
 *   BlueZ, git.kernel.org/pub/scm/bluetooth/bluez.git, snapshot commit
 *   92305dc06ab8a6d89af2dae1d725cc4d51462ad1:
 *     BlueZ is host-only over the Linux kernel; the LE event mask is set by
 *     the kernel, not by BlueZ userspace, so BlueZ contributes no mask
 *     construction to compare.  It does read the Supported Commands bitmap
 *     (tools/btinfo.c:140, tools/hciconfig.c:1099).
 */
#ifndef TESTS_BLUETOOTH_SPEC_EXTREF_HCI_LE_EVENT_MASK_H
#define TESTS_BLUETOOTH_SPEC_EXTREF_HCI_LE_EVENT_MASK_H

#include <stdint.h>

/*
 * Core 6.3, Vol 4, Part E, Section 7.8.1, LE_Event_Mask bit table, transcribed
 * from text lines 111788-111860.  Truncated at bit 38: everything from bit 35
 * upwards is a [v2] event or a 5.4+/6.x feature and is out of scope for a
 * 5.2 + Connection Subrating target, but bits 35-38 are listed so that a
 * reader does not mistake bit 34 for the end of the table.
 */
#define BT_EXTREF_LE_EVTMASK_CONN_COMPLETE		0	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_ADV_REPORT			1
#define BT_EXTREF_LE_EVTMASK_CONN_UPDATE_COMPLETE	2
#define BT_EXTREF_LE_EVTMASK_READ_REMOTE_FEAT_COMPLETE	3
#define BT_EXTREF_LE_EVTMASK_LTK_REQUEST		4
#define BT_EXTREF_LE_EVTMASK_REMOTE_CONN_PARAM_REQ	5
#define BT_EXTREF_LE_EVTMASK_DATA_LENGTH_CHANGE		6
#define BT_EXTREF_LE_EVTMASK_READ_LOCAL_P256_COMPLETE	7
#define BT_EXTREF_LE_EVTMASK_GENERATE_DHKEY_COMPLETE	8
#define BT_EXTREF_LE_EVTMASK_ENH_CONN_COMPLETE		9	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_DIRECTED_ADV_REPORT	10
#define BT_EXTREF_LE_EVTMASK_PHY_UPDATE_COMPLETE	11
#define BT_EXTREF_LE_EVTMASK_EXT_ADV_REPORT		12
#define BT_EXTREF_LE_EVTMASK_PER_ADV_SYNC_ESTABLISHED	13	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_PER_ADV_REPORT		14	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_PER_ADV_SYNC_LOST		15
#define BT_EXTREF_LE_EVTMASK_SCAN_TIMEOUT		16
#define BT_EXTREF_LE_EVTMASK_ADV_SET_TERMINATED		17
#define BT_EXTREF_LE_EVTMASK_SCAN_REQUEST_RECEIVED	18
#define BT_EXTREF_LE_EVTMASK_CHANNEL_SEL_ALGORITHM	19
#define BT_EXTREF_LE_EVTMASK_CONNECTIONLESS_IQ_REPORT	20
#define BT_EXTREF_LE_EVTMASK_CONNECTION_IQ_REPORT	21
#define BT_EXTREF_LE_EVTMASK_CTE_REQUEST_FAILED		22
#define BT_EXTREF_LE_EVTMASK_PAST_RECEIVED		23	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_CIS_ESTABLISHED		24	/* [v1] */
#define BT_EXTREF_LE_EVTMASK_CIS_REQUEST		25
#define BT_EXTREF_LE_EVTMASK_CREATE_BIG_COMPLETE	26
#define BT_EXTREF_LE_EVTMASK_TERMINATE_BIG_COMPLETE	27
#define BT_EXTREF_LE_EVTMASK_BIG_SYNC_ESTABLISHED	28
#define BT_EXTREF_LE_EVTMASK_BIG_SYNC_LOST		29
#define BT_EXTREF_LE_EVTMASK_REQUEST_PEER_SCA_COMPLETE	30
#define BT_EXTREF_LE_EVTMASK_PATH_LOSS_THRESHOLD	31
#define BT_EXTREF_LE_EVTMASK_TX_POWER_REPORTING		32
#define BT_EXTREF_LE_EVTMASK_BIGINFO_ADV_REPORT		33
#define BT_EXTREF_LE_EVTMASK_SUBRATE_CHANGE		34
/* Out of scope for 5.2 + subrating; listed only to bound the table. */
#define BT_EXTREF_LE_EVTMASK_PER_ADV_SYNC_ESTAB_V2	35
#define BT_EXTREF_LE_EVTMASK_PER_ADV_REPORT_V2		36
#define BT_EXTREF_LE_EVTMASK_PAST_RECEIVED_V2		37
#define BT_EXTREF_LE_EVTMASK_PER_ADV_SUBEVENT_DATA_REQ	38

/*
 * The highest mask bit that a 5.2 + Connection Subrating host may need.
 * Bit 34 (Subrate Change) is the Connection Subrating addition.
 */
#define BT_EXTREF_LE_EVTMASK_MAX_BIT_IN_SCOPE		34

/*
 * "The default is for just bits 0 to 4 to be set."  Section 7.8.1, text line
 * ~111857.  Any subevent above bit 4 that a host wants MUST be unmasked
 * explicitly; there is no implicit enablement.
 */
#define BT_EXTREF_LE_EVTMASK_SPEC_DEFAULT		UINT64_C(0x000000000000001f)

/*
 * Section 7.8.1: "The Controller shall ignore those bits which are reserved
 * for future use or represent events which it does not support."  1 = setting
 * a bit for an unsupported event is safe and cannot fail the command.
 *
 * Consequence for a test: a host is never REQUIRED to gate a mask bit on a
 * feature bit, so a missing gate is not a defect, but a WRONG gate always is.
 */
#define BT_EXTREF_LE_EVTMASK_UNSUPPORTED_BITS_IGNORED	1

/*
 * Section 7.8.1: LE events are gated a second time by the LE Meta event bit in
 * the (non-LE) Event_Mask.  Vol 4, Part E, Section 7.3.1, LE Meta event is
 * bit 61.
 */
#define BT_EXTREF_EVTMASK_LE_META_BIT			61

/*
 * Vol 6, Part B, Section 5.1.7.2: the on-air consequence of leaving bit 5
 * masked when the peer runs the Connection Parameters Request procedure and
 * the Link Layer needs to consult the Host.  This is why bit 5 is not
 * cosmetic.
 */
#define BT_EXTREF_LE_EVTMASK_BIT5_MASKED_LL_REJECT_ERROR	0x1a	/* Unsupported
								   Remote
								   Feature */

/*
 * Which subevents a host must ALSO be able to act on once it unmasks the bit.
 * Bit 5 is the only one in the in-scope range that obliges the host to answer
 * with a command; if it is unmasked and not answered, the peer's procedure
 * stalls until its LL procedure response timeout.
 *
 * OCFs from Vol 4, Part E, Sections 7.8.31 and 7.8.32 (OGF 0x08).
 */
#define BT_EXTREF_LE_OCF_REMOTE_CONN_PARAM_REQ_REPLY	0x0020
#define BT_EXTREF_LE_OCF_REMOTE_CONN_PARAM_REQ_NEG_REPLY 0x0021

/*
 * Reference gating strategy.  0 = does not gate (or does not build the mask),
 * 1 = gates on the HCI version, 2 = gates on LE feature bits.
 *
 * Recorded because the two gating strategies disagree about controllers that
 * report a high HCI version but clear the corresponding feature bit, and
 * because a reader comparing 5BSD against only one reference would conclude
 * the other strategy is wrong.  Section 7.8.1 permits either, and permits
 * neither.
 */
#define BT_EXTREF_LE_EVTMASK_GATING_NIMBLE		1	/* ble_hs_startup.c:206,212-330 */
#define BT_EXTREF_LE_EVTMASK_GATING_ZEPHYR		2	/* hci_core.c:3765-3766 */
#define BT_EXTREF_LE_EVTMASK_GATING_BLUEZ		0	/* kernel-side */

/*
 * Bits that NimBLE sets for every controller at or above the stated HCI
 * version, transcribed from ble_hs_startup.c:212-251.  A host targeting the
 * same controller population and NOT setting these is delivering strictly
 * fewer events than the most conservative reference.
 */
#define BT_EXTREF_LE_EVTMASK_NIMBLE_AT_4_1		UINT64_C(0x000000000000003f)
#define BT_EXTREF_LE_EVTMASK_NIMBLE_AT_4_2		UINT64_C(0x000000000000067f)
#define BT_EXTREF_LE_EVTMASK_NIMBLE_AT_5_0		UINT64_C(0x00000000000ffe7f)

#endif /* TESTS_BLUETOOTH_SPEC_EXTREF_HCI_LE_EVENT_MASK_H */
