/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Test-only ATT client wire oracles from Bluetooth Core 6.3 Vol 3,
 * Part F §§3.3-3.4 and Table 3.42, Vol 3 Part G §5.3, and Assigned Numbers.
 * No production headers are included.
 */
#ifndef TESTS_BLUETOOTH_SPEC_ATT_CLIENT_ORACLES_H
#define TESTS_BLUETOOTH_SPEC_ATT_CLIENT_ORACLES_H

#include "spec_core63_generated.h"

/*
 * Generated Core tables expanded into a test-only namespace.  The suffixes
 * intentionally mirror the implementation names so peer-PDU fixtures can be
 * mechanically audited without importing their values from att.h.
 */
#define BT_CORE63_ATT_WIRE_ENUM(name, value) BT_CORE63_WIRE_##name = value,
enum {
	BT_CORE63_ATT_ORACLES(BT_CORE63_ATT_WIRE_ENUM)
	BT_CORE63_ATT_ERROR_ORACLES(BT_CORE63_ATT_WIRE_ENUM)
	/* Core 6.3 Table 3.42: previously-used Signed Write Command assignment. */
	BT_CORE63_WIRE_ATT_OP_LEGACY_SIGNED_WRITE_CMD = 0xd2,
};
#undef BT_CORE63_ATT_WIRE_ENUM

#define BT_CORE63_ATT_OP_ERROR_RSP		0x01
#define BT_CORE63_ATT_OP_MTU_REQ		0x02
#define BT_CORE63_ATT_OP_MTU_RSP		0x03
#define BT_CORE63_ATT_OP_FIND_INFO_REQ		0x04
#define BT_CORE63_ATT_OP_FIND_INFO_RSP		0x05
#define BT_CORE63_ATT_OP_FIND_BY_TYPE_VALUE_REQ	0x06
#define BT_CORE63_ATT_OP_FIND_BY_TYPE_VALUE_RSP	0x07
#define BT_CORE63_ATT_OP_READ_BY_TYPE_RSP	0x09
#define BT_CORE63_ATT_OP_READ_BY_TYPE_REQ	0x08
#define BT_CORE63_ATT_OP_READ_REQ		0x0a
#define BT_CORE63_ATT_OP_READ_RSP		0x0b
#define BT_CORE63_ATT_OP_READ_BLOB_REQ		0x0c
#define BT_CORE63_ATT_OP_READ_BLOB_RSP		0x0d
#define BT_CORE63_ATT_OP_READ_MULTIPLE_REQ	0x0e
#define BT_CORE63_ATT_OP_READ_MULTIPLE_RSP	0x0f
#define BT_CORE63_ATT_OP_READ_BY_GROUP_TYPE_RSP	0x11
#define BT_CORE63_ATT_OP_READ_BY_GROUP_TYPE_REQ	0x10
#define BT_CORE63_ATT_OP_WRITE_REQ		0x12
#define BT_CORE63_ATT_OP_WRITE_RSP		0x13
#define BT_CORE63_ATT_OP_PREPARE_WRITE_REQ	0x16
#define BT_CORE63_ATT_OP_PREPARE_WRITE_RSP	0x17
#define BT_CORE63_ATT_OP_EXECUTE_WRITE_REQ	0x18
#define BT_CORE63_ATT_OP_EXECUTE_WRITE_RSP	0x19
#define BT_CORE63_ATT_OP_HANDLE_NOTIFY		0x1b
#define BT_CORE63_ATT_OP_HANDLE_INDICATE	0x1d
#define BT_CORE63_ATT_OP_HANDLE_CONFIRM		0x1e
#define BT_CORE63_ATT_OP_READ_MULTIPLE_VARIABLE_REQ 0x20
#define BT_CORE63_ATT_OP_READ_MULTIPLE_VARIABLE_RSP 0x21
#define BT_CORE63_ATT_OP_MULTIPLE_HANDLE_NOTIFY	0x23
#define BT_CORE63_ATT_OP_WRITE_CMD		0x52

/* Vol 3 Part F §3.3.1 Table 3.2 opcode field masks. */
#define BT_CORE63_ATT_OPCODE_METHOD_MASK	0x3f

/* Assigned Numbers: declaration, service, and characteristic UUIDs. */
#define BT_ASSIGNED_UUID_PRIMARY_SERVICE	0x2800
#define BT_ASSIGNED_UUID_SECONDARY_SERVICE	0x2801
#define BT_ASSIGNED_UUID_CHARACTERISTIC		0x2803
#define BT_ASSIGNED_UUID_INCLUDE		0x2802
#define BT_ASSIGNED_UUID_CHARACTERISTIC		0x2803
#define BT_ASSIGNED_UUID_CCCD			0x2902
#define BT_ASSIGNED_UUID_CHARACTERISTIC_USER_DESC 0x2901
#define BT_ASSIGNED_UUID_GAP_SERVICE		0x1800
#define BT_ASSIGNED_UUID_GATT_SERVICE		0x1801
#define BT_ASSIGNED_UUID_DEVICE_INFORMATION	0x180a
#define BT_ASSIGNED_UUID_BATTERY_SERVICE		0x180f
#define BT_ASSIGNED_UUID_DEVICE_NAME		0x2a00
#define BT_ASSIGNED_UUID_APPEARANCE		0x2a01
#define BT_ASSIGNED_UUID_SERVICE_CHANGED	0x2a05
#define BT_ASSIGNED_UUID_GLUCOSE_MEASUREMENT	0x2a18
#define BT_ASSIGNED_UUID_BATTERY_LEVEL		0x2a19
#define BT_ASSIGNED_UUID_CLIENT_SUPPORTED_FEATURES 0x2b29
#define BT_ASSIGNED_UUID_DATABASE_HASH		0x2b2a
#define BT_ASSIGNED_UUID_GLUCOSE_SERVICE	0x1808
#define BT_ASSIGNED_UUID_CHARACTERISTIC_EXT_PROPS 0x2900

/* Vol 3 Part G §3.3.1/Table 3.5 characteristic property bit. */
#define BT_CORE63_GATT_PROP_READ		0x02
#define BT_CORE63_GATT_PROP_WRITE_NO_RSP	0x04
#define BT_CORE63_GATT_PROP_WRITE		0x08
#define BT_CORE63_GATT_PROP_NOTIFY		0x10
#define BT_CORE63_GATT_PROP_INDICATE		0x20

/* Vol 3 Part G §3.3.3.3 Table 3.11. */
#define BT_CORE63_GATT_CCCD_NOTIFY		0x0001
#define BT_CORE63_GATT_CCCD_INDICATE		0x0002
#define BT_CORE63_GATT_CCCD_DEFINED_MASK	0x0003

/* Vol 3 Part F §3.4.1.1 Table 3.4. */
#define BT_CORE63_ATT_ERR_INVALID_HANDLE	0x01
#define BT_CORE63_ATT_ERR_READ_NOT_PERMITTED	0x02
#define BT_CORE63_ATT_ERR_WRITE_NOT_PERMITTED	0x03
#define BT_CORE63_ATT_ERR_INVALID_PDU		0x04
#define BT_CORE63_ATT_ERR_INSUFFICIENT_AUTHENTICATION 0x05
#define BT_CORE63_ATT_ERR_REQUEST_NOT_SUPPORTED 0x06
#define BT_CORE63_ATT_ERR_INVALID_OFFSET	0x07
#define BT_CORE63_ATT_ERR_PREPARE_QUEUE_FULL	0x09
#define BT_CORE63_ATT_ERR_ATTRIBUTE_NOT_FOUND	0x0a
#define BT_CORE63_ATT_ERR_ATTRIBUTE_NOT_LONG	0x0b
#define BT_CORE63_ATT_ERR_INSUFFICIENT_ENCRYPTION 0x0f
#define BT_CORE63_ATT_ERR_UNSUPPORTED_GROUP_TYPE 0x10
#define BT_CORE63_ATT_ERR_INVALID_ATTRIBUTE_LENGTH 0x0d
#define BT_CORE63_ATT_ERR_VALUE_NOT_ALLOWED	0x13

/* Vol 3 Part F §§3.4.1.1, 3.4.2, 3.4.4.3-3.4.5.3. */
#define BT_CORE63_ATT_DEFAULT_MTU	23
#define BT_CORE63_ATT_MTU_PDU_SIZE	3
#define BT_CORE63_ATT_READ_REQ_SIZE	3
#define BT_CORE63_ATT_READ_BLOB_REQ_SIZE 5
#define BT_CORE63_ATT_READ_MULTIPLE_MIN_REQ_SIZE 5
#define BT_CORE63_ATT_ERROR_RSP_SIZE	5
#define BT_CORE63_ATT_OPCODE_SIZE	1
#define BT_CORE63_ATT_RESPONSE_PARAM_HEADER_SIZE 1
#define BT_CORE63_ATT_HANDLE_VALUE_HEADER_SIZE 3
#define BT_CORE63_ATT_LENGTH_VALUE_HEADER_SIZE 2
#define BT_CORE63_ATT_WRITE_HEADER_SIZE	3
#define BT_CORE63_ATT_PREPARE_WRITE_HEADER_SIZE 5
#define BT_CORE63_ATT_HANDLE_LENGTH_VALUE_HEADER_SIZE 4
#define BT_CORE63_ATT_FIND_INFO_REQ_SIZE	5
#define BT_CORE63_ATT_FIND_INFO_FORMAT_UUID16 0x01
#define BT_CORE63_ATT_FIND_INFO_UUID16_ENTRY_SIZE 4
#define BT_CORE63_ATT_FIND_BY_TYPE_VALUE_PREFIX_SIZE 7
#define BT_CORE63_ATT_FIND_BY_TYPE_VALUE_ENTRY_SIZE 4
#define BT_CORE63_ATT_RANGE_UUID16_REQ_SIZE 7
#define BT_CORE63_ATT_RANGE_UUID128_REQ_SIZE 21
#define BT_CORE63_ATT_RANGE_PREFIX_SIZE	5
#define BT_CORE63_ATT_UUID16_SIZE	2
#define BT_CORE63_ATT_UUID32_SIZE	4
#define BT_CORE63_ATT_EXECUTE_WRITE_REQ_SIZE 2
#define BT_CORE63_ATT_EXECUTE_WRITE_CANCEL 0x00
#define BT_CORE63_ATT_EXECUTE_WRITE_COMMIT 0x01
#define BT_CORE63_ATT_EXECUTE_WRITE_FIRST_RFU 0x02

/*
 * Core 5.2 Vol 3 Part F §3.4.5.4 and Vol 3 Part H §2.4.5 define the
 * legacy opcode/signature fields.  Core 6.3 Vol 1 Part E §2.4.2 and Vol 3
 * Part F Table 3.42 mark them previously used.  These constants describe
 * retained compatibility only, not a current-Core ATT method.
 */
#define BT_CORE63_LEGACY_ATT_OP_SIGNED_WRITE_CMD 0xd2
#define BT_CORE63_LEGACY_ATT_SIGN_COUNTER_SIZE 4
#define BT_CORE63_LEGACY_ATT_MAC_SIZE 8
#define BT_CORE63_LEGACY_ATT_SIGNATURE_SIZE 12
#define BT_CORE63_LEGACY_ATT_SIGNED_WRITE_MIN_SIZE \
	(BT_CORE63_ATT_WRITE_HEADER_SIZE + \
	BT_CORE63_LEGACY_ATT_SIGNATURE_SIZE)

/* Vol 3 Part F §3.2.9 and response layouts in §§3.4.3-3.4.4. */
#define BT_CORE63_ATT_MAX_MTU		517
#define BT_CORE63_ATT_HANDLE_MAX		0xffff
#define BT_CORE63_ATT_UUID128_SIZE	16
#define BT_CORE63_ATT_UUID128_TRUNCATED_SIZE 15
#define BT_CORE63_ATT_DB_HASH_SIZE	16
#define BT_CORE63_ATT_RBT_HEADER_SIZE	2
#define BT_CORE63_ATT_GROUP16_ENTRY_SIZE	6
#define BT_CORE63_ATT_INCLUDE16_ENTRY_SIZE 8
#define BT_CORE63_ATT_INCLUDE128_ENTRY_SIZE 6
#define BT_CORE63_ATT_CHAR16_ENTRY_SIZE	7
#define BT_CORE63_ATT_FIND_INFO_UUID16_ENTRY_SIZE 4
#define BT_CORE63_ATT_FIND_INFO_UUID128_ENTRY_SIZE 18
#define BT_CORE63_ATT_DB_HASH_ENTRY_SIZE	18

/* Core 6.3 Vol 3 Part G §5.3: Enhanced ATT bearer minimum MTU. */
#define BT_CORE63_EATT_MIN_MTU	64

/* Bluetooth SIG Assigned Numbers: Enhanced Attribute Protocol fixed PSM. */
#define BT_ASSIGNED_EATT_PSM	0x0027

#endif /* TESTS_BLUETOOTH_SPEC_ATT_CLIENT_ORACLES_H */
