#
# The pkg(8) repository configuration file for the 5BSD installation DVD.
#

5BSD_install_cdrom: {
  url: "file:///dist/packages/${ABI}",
  mirror_type: "none",
  enabled: yes
}

FreeBSD: {
  enabled: no
}
