# mptable: broken (not 64 bit clean)
# pnpinfo: crashes (not really useful anyway)
.if ${MK_ACPI} != "no"
SUBDIR+=	acpi
.endif
.if ${MK_APM} != "no"
SUBDIR+=	apm
.endif
.if ${MK_BHYVE} != "no"
SUBDIR+=	bhyve
SUBDIR+=	virtiofsd
SUBDIR+=	bhyvectl
SUBDIR+=	bhyveload
.endif
SUBDIR+=	boot0cfg
# bsdtrace links libipt, which is MK_PMC-gated (see lib/Makefile).
.if ${MK_PMC} != "no"
SUBDIR+=	bsdtrace
.endif
.if ${MK_TOOLCHAIN} != "no"
SUBDIR+=	btxld
.endif
SUBDIR+=	cpucontrol
SUBDIR+=	lptcontrol
SUBDIR+=	mptable
SUBDIR+=	spkrtest
SUBDIR+=	zzz
