#! /bin/sh

# Build Open Container Initiative (OCI) container image suitable as a base for
# dynamic-linked workloads. This adds libraries from the 5BSD-clibs and
# 5BSD-openssl-lib packages.

OCI_BASE_IMAGE=static

oci_image_build() {
	install_packages ${abi} ${workdir} \
	    ${pkg_prefix}-clibs ${pkg_prefix}-openssl-lib
}
