# SPDX-License-Identifier: BSD-2-Clause
# Pi 4: pkgbase built with KERNCONF=VBSD-RPI, ZFS root, u-boot-rpi4.
# See release/tools/rpi-wifi-testing.md for assets and firmware preparation.
VMFS=zfs
IMAGE_HOSTNAME=5bsd-rpi4
RPI_BOARD=rpi4
RPI_DTB=bcm2711-rpi-4-b.dtb
RPI_BOOT_FILES="start4.elf fixup4.dat armstub8-gic.bin"
RPI_WIFI_DTS=5bsd-rpi4-wifi.dts
RPI_ARMSTUB=armstub8-gic.bin
RPI_FAT_LABEL=5BSD_RPI4
. "${RPI_TOOLS_DIR:-${scriptdir}/../tools}/rpi.subr"
