.include <src.opts.mk>

PACKAGE=	tests
TESTSDIR=	${TESTSBASE}/lib/libcapability

ATF_TESTS_SH=	libcapability_test

${PACKAGE}FILES+=	libcapability_test.sh
${PACKAGE}FILESMODE_libcapability_test.sh=	0555

.include <bsd.test.mk>
