/*-
 * SPDX-License-Identifier: BSD-2-Clause
 */

#ifndef _DEV_VMM_VMM_STARTUP_MODE_H_
#define	_DEV_VMM_VMM_STARTUP_MODE_H_

#include <sys/types.h>

#ifndef _KERNEL
#include <stdbool.h>
#include <stdint.h>
#endif

#include <dev/vmm/vmm_startup_event.h>

/*
 * Private, machine-independent selection and decision values for virtual
 * INIT/SIPI delivery.  The default preserves the historical userspace exit
 * contract.  Kernel ownership is selected explicitly and frozen before the
 * first vCPU run; this value does not itself apply architectural state or
 * provide a saved-state format.
 */
enum vmm_startup_owner {
	VMM_STARTUP_OWNER_USERSPACE = 0,
	VMM_STARTUP_OWNER_KERNEL,
	VMM_STARTUP_OWNER_LAST,
};

/*
 * The execution contract is distinct from architectural ownership.  The
 * historical userspace owner resumes AP threads from the IPI exit handler.
 * A kernel owner is valid only when userspace has explicitly arranged for
 * every configured vCPU thread to enter VM_RUN and wait in the kernel.
 */
enum vmm_startup_execution {
	VMM_STARTUP_EXECUTION_USERSPACE_RESUME = 0,
	VMM_STARTUP_EXECUTION_PRESTARTED_WAIT,
	VMM_STARTUP_EXECUTION_LAST,
};

enum vmm_startup_action {
	VMM_STARTUP_ACTION_NONE = 0,
	VMM_STARTUP_ACTION_EXIT_USERSPACE_INIT,
	VMM_STARTUP_ACTION_EXIT_USERSPACE_SIPI,
	VMM_STARTUP_ACTION_APPLY_KERNEL_INIT,
	VMM_STARTUP_ACTION_APPLY_KERNEL_SIPI,
	VMM_STARTUP_ACTION_DISCARD_SIPI,
	VMM_STARTUP_ACTION_LAST,
};

/*
 * Machine-dependent processing of one kernel-owned startup event reports one
 * of these machine-independent outcomes.  RETAINED is not a busy wait: the
 * exact event remains owned while the guest is allowed to run and remove a
 * live architectural blocker.  CONSUMED requires common lifecycle and
 * wait-for-SIPI predicates to be replayed before any guest re-entry.
 */
enum vmm_startup_dispatch_result {
	VMM_STARTUP_DISPATCH_IDLE = 0,
	VMM_STARTUP_DISPATCH_RETAINED,
	VMM_STARTUP_DISPATCH_CONSUMED,
	VMM_STARTUP_DISPATCH_RESULT_LAST,
};

struct vmm_startup_mode {
	uint8_t owner;
	uint8_t execution;
	uint8_t locked;
	uint8_t reserved8;
	uint32_t reserved32;
};

struct vmm_startup_action_plan {
	uint8_t action;
	uint8_t startup_wait;
	uint16_t reserved16;
	uint32_t reserved32;
};

struct vmm_startup_dispatch_plan {
	uint8_t enter_guest;
	uint8_t replay_lifecycle;
	uint16_t reserved16;
	uint32_t reserved32;
};

/*
 * Pure routing decision for one published INIT/SIPI target set.  The locked
 * owner selection plus the caller-sampled coordinator observations produce
 * exactly one delivery route.  The userspace route authorizes only the
 * historical VM_EXITCODE_IPI/SPINUP_AP exit contract and never publishes
 * kernel event state.  The kernel route requires the caller to publish the
 * whole target set atomically before acting on the decision.  A rejected
 * decision leaves the output untouched, so a failed routing attempt cannot
 * leak a partial route that a fallback could deliver twice.
 */
struct vmm_startup_delivery {
	uint8_t owner;
	uint8_t kernel_publication;
	uint16_t reserved16;
	uint32_t reserved32;
};

enum vmm_startup_entry_action {
	VMM_STARTUP_ENTRY_DISPATCH = 0,
	VMM_STARTUP_ENTRY_SERVICE_RENDEZVOUS,
	VMM_STARTUP_ENTRY_SERVICE_SUSPEND,
	VMM_STARTUP_ENTRY_SERVICE_REQIDLE,
	VMM_STARTUP_ENTRY_RETURN_DEBUG,
	VMM_STARTUP_ENTRY_WAIT,
	VMM_STARTUP_ENTRY_ENTER_GUEST,
	VMM_STARTUP_ENTRY_REPLAY,
	VMM_STARTUP_ENTRY_ACTION_LAST,
};

struct vmm_startup_entry_snapshot {
	uint8_t rendezvous;
	uint8_t suspended;
	uint8_t reqidle;
	uint8_t debugged;
	uint8_t waiting;
	uint8_t reserved8[3];
	uint32_t reserved32;
};

int	vmm_startup_entry_snapshot_validate(
	    const struct vmm_startup_entry_snapshot *);

/*
 * Runtime-only observation passed from the frozen entry planner to the final
 * interrupt-disabled machine-entry check.  Admission compares observations
 * made before and after dispatch, accounting for only the exact notification
 * generated by a consumed claim.  It is not save state or an ABI.
 */
struct vmm_startup_entry_handoff {
	uint64_t notification_generation;
	uint32_t armed;
	uint32_t reserved;
};

/*
 * Failure-atomic result of the complete FROZEN dispatch-admission
 * transaction.  A handoff is armed only when action is ENTER_GUEST.  All
 * other actions carry an empty handoff.  This is transient kernel control
 * state, not save state or a public ABI.
 */
struct vmm_startup_entry_admission {
	struct vmm_startup_entry_handoff handoff;
	uint8_t action;
	uint8_t reserved8[3];
	uint32_t reserved32;
};

enum vmm_startup_entry_runtime_phase {
	VMM_STARTUP_ENTRY_RUNTIME_FROZEN = 0,
	VMM_STARTUP_ENTRY_RUNTIME_CRITICAL,
	VMM_STARTUP_ENTRY_RUNTIME_GUEST_FPU,
	VMM_STARTUP_ENTRY_RUNTIME_RUNNING,
	VMM_STARTUP_ENTRY_RUNTIME_CHECKED,
	VMM_STARTUP_ENTRY_RUNTIME_REFROZEN,
	VMM_STARTUP_ENTRY_RUNTIME_HOST_FPU,
	VMM_STARTUP_ENTRY_RUNTIME_COMPLETE,
	VMM_STARTUP_ENTRY_RUNTIME_PHASE_LAST,
};

enum vmm_startup_entry_runtime_action {
	VMM_STARTUP_ENTRY_RUNTIME_ENTER_GUEST = 0,
	VMM_STARTUP_ENTRY_RUNTIME_REPLAY,
	VMM_STARTUP_ENTRY_RUNTIME_RETURN_ERROR,
	VMM_STARTUP_ENTRY_RUNTIME_ACTION_LAST,
};

struct vmm_startup_entry_runtime {
	uint8_t phase;
	uint8_t critical;
	uint8_t guest_fpu;
	uint8_t running;
	uint32_t reserved;
};

struct vmm_startup_entry_runtime_result {
	int32_t error;
	uint8_t action;
	uint8_t reserved8[3];
};

/*
 * Architecture-neutral model for one synchronous machine-run call.  A
 * backend must perform a fresh guard check before every hardware entry,
 * including after an exit it handled internally.  This is transient control
 * state, not a saved-state or public ABI.
 */
enum vmm_startup_entry_loop_phase {
	VMM_STARTUP_ENTRY_LOOP_NEED_CHECK = 0,
	VMM_STARTUP_ENTRY_LOOP_CHECKED,
	VMM_STARTUP_ENTRY_LOOP_IN_GUEST,
	VMM_STARTUP_ENTRY_LOOP_RETURNABLE,
	VMM_STARTUP_ENTRY_LOOP_COMPLETE,
	VMM_STARTUP_ENTRY_LOOP_PHASE_LAST,
};

enum vmm_startup_entry_loop_action {
	VMM_STARTUP_ENTRY_LOOP_RETURN_VMEXIT = 0,
	VMM_STARTUP_ENTRY_LOOP_RETURN_SOFTWARE_EXIT,
	VMM_STARTUP_ENTRY_LOOP_REPLAY,
	VMM_STARTUP_ENTRY_LOOP_RETURN_ERROR,
	VMM_STARTUP_ENTRY_LOOP_ACTION_LAST,
};

struct vmm_startup_entry_loop_result {
	int32_t error;
	uint8_t action;
	uint8_t reserved8[3];
};

struct vmm_startup_entry_loop {
	uint64_t check_count;
	uint64_t entry_count;
	struct vmm_startup_entry_loop_result disposition;
	uint8_t phase;
	uint8_t reserved8[7];
};

void	vmm_startup_mode_init(struct vmm_startup_mode *);
int	vmm_startup_mode_validate(const struct vmm_startup_mode *);
int	vmm_startup_mode_configure(struct vmm_startup_mode *,
	    enum vmm_startup_owner);
int	vmm_startup_mode_configure_execution(struct vmm_startup_mode *,
	    enum vmm_startup_execution);
int	vmm_startup_mode_lock(struct vmm_startup_mode *);
int	vmm_startup_action_plan(const struct vmm_startup_mode *,
	    enum vmm_startup_event_kind, bool, bool,
	    struct vmm_startup_action_plan *);
int	vmm_startup_delivery_validate(const struct vmm_startup_delivery *);
int	vmm_startup_delivery_decide(const struct vmm_startup_mode *,
	    enum vmm_startup_event_kind, uint8_t, size_t, bool, bool,
	    struct vmm_startup_delivery *);
int	vmm_startup_dispatch_plan(enum vmm_startup_dispatch_result,
	    struct vmm_startup_dispatch_plan *);
int	vmm_startup_entry_pre_dispatch(
	    const struct vmm_startup_entry_snapshot *,
	    enum vmm_startup_entry_action *);
int	vmm_startup_entry_post_dispatch(
	    const struct vmm_startup_entry_snapshot *,
	    enum vmm_startup_dispatch_result,
	    enum vmm_startup_entry_action *);
int	vmm_startup_entry_handoff_validate(
	    const struct vmm_startup_entry_handoff *);
int	vmm_startup_entry_handoff_capture(uint64_t,
	    enum vmm_startup_dispatch_result, uint64_t,
	    struct vmm_startup_entry_handoff *);
int	vmm_startup_entry_handoff_check(uint64_t,
	    const struct vmm_startup_entry_handoff *);
int	vmm_startup_entry_handoff_disarm(uint64_t,
	    struct vmm_startup_entry_handoff *);
int	vmm_startup_entry_admission_validate(
	    const struct vmm_startup_entry_admission *);
int	vmm_startup_entry_dispatch_admit(
	    const struct vmm_startup_entry_snapshot *,
	    const struct vmm_startup_entry_snapshot *,
	    enum vmm_startup_dispatch_result, uint64_t, uint64_t,
	    struct vmm_startup_entry_admission *);
uint64_t vmm_startup_notification_generation_capture(uint64_t);
int	vmm_startup_notification_advance(uint64_t, uint64_t *);
void	vmm_startup_entry_runtime_init(struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_validate(
	    const struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_enter_critical(
	    struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_restore_guest_fpu(
	    struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_publish_running(
	    struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_check(
	    struct vmm_startup_entry_runtime *, int, int,
	    struct vmm_startup_entry_runtime_result *);
int	vmm_startup_entry_runtime_publish_frozen(
	    struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_save_guest_fpu(
	    struct vmm_startup_entry_runtime *);
int	vmm_startup_entry_runtime_exit_critical(
	    struct vmm_startup_entry_runtime *);
void	vmm_startup_entry_loop_init(struct vmm_startup_entry_loop *);
int	vmm_startup_entry_loop_validate(
	    const struct vmm_startup_entry_loop *);
int	vmm_startup_entry_loop_check(struct vmm_startup_entry_loop *,
	    const struct vmm_startup_entry_runtime_result *);
int	vmm_startup_entry_loop_enter(struct vmm_startup_entry_loop *);
/*
 * A backend may have completed final machine-local preparation but not yet
 * know whether an attempted hardware entry executed guest instructions.
 * Return from that checked, unentered attempt without inventing an entry.
 */
int	vmm_startup_entry_loop_software_exit_checked(
	    struct vmm_startup_entry_loop *,
	    struct vmm_startup_entry_loop_result *);
/*
 * A checked hardware attempt was conclusively unentered but its adapter
 * reports a terminal error.  EAGAIN is deliberately rejected: it cannot
 * prove that retrying would not duplicate an entry attempt.
 */
int	vmm_startup_entry_loop_fail_checked(struct vmm_startup_entry_loop *,
	    int, struct vmm_startup_entry_loop_result *);
int	vmm_startup_entry_loop_exit(struct vmm_startup_entry_loop *, bool,
	    int);
int	vmm_startup_entry_loop_software_exit(
	    struct vmm_startup_entry_loop *,
	    struct vmm_startup_entry_loop_result *);
int	vmm_startup_entry_loop_fail_before_entry(
	    struct vmm_startup_entry_loop *, int,
	    struct vmm_startup_entry_loop_result *);
int	vmm_startup_entry_loop_finish(struct vmm_startup_entry_loop *,
	    struct vmm_startup_entry_loop_result *);
int	vmm_startup_entry_guard_before(struct vmm_startup_entry_runtime *,
	    struct vmm_startup_entry_loop *, int, int,
	    struct vmm_startup_entry_runtime_result *);
int	vmm_startup_entry_guard_after(struct vmm_startup_entry_loop *, bool,
	    int, struct vmm_startup_entry_loop_result *);
int	vmm_startup_entry_guard_complete(
	    const struct vmm_startup_entry_loop_result *, int, int,
	    struct vmm_startup_entry_loop_result *);

#endif /* _DEV_VMM_VMM_STARTUP_MODE_H_ */
