.include <src.opts.mk>

TESTSDIR=	${TESTSBASE}/lib/libappbundle

ATF_TESTS_SH=	libappbundle_test

${PACKAGE}FILES+=	libappbundle_test.sh
${PACKAGE}FILESMODE_libappbundle_test.sh=	0555

.include <bsd.test.mk>
