PACKAGE=	tests

ATF_TESTS_SH+=	oracled_test
ATF_TESTS_SH+=	oracled_init_test
ATF_TESTS_SH+=	oracled_bootstrap_test
ATF_TESTS_SH+=	oracled_svc_test
ATF_TESTS_SH+=	oracled_stress_test

.include <bsd.test.mk>
