/*
 * Independent VirtIO 1.4 test oracle.
 *
 * Do not define these values in terms of FreeBSD or bhyve macros.  Tests use
 * them to detect drift between the implementation and the published wire
 * protocol.  Section references are to OASIS VirtIO 1.4 Committee
 * Specification 01, 2026-04-08, matching /tmp/virtio-v1.4.html with SHA-256
 * acc3f9cb42ea8660efad1aa67a69d142568970dc10b245a051c9b54194e90f2a.
 */
#ifndef _VIRTIO_1_4_SPEC_H_
#define _VIRTIO_1_4_SPEC_H_

#include <stdint.h>

/* 2.1: Device Status Field. */
#define	VIRTIO14_STATUS_ACKNOWLEDGE	0x01U
#define	VIRTIO14_STATUS_DRIVER		0x02U
#define	VIRTIO14_STATUS_DRIVER_OK	0x04U
#define	VIRTIO14_STATUS_FEATURES_OK	0x08U
#define	VIRTIO14_STATUS_SUSPEND		0x10U
#define	VIRTIO14_STATUS_RESERVED_MASK	0x20U
#define	VIRTIO14_STATUS_DEVICE_NEEDS_RESET 0x40U
#define	VIRTIO14_STATUS_FAILED		0x80U

/* 2.2: Feature Bits. */
#define	VIRTIO14_F_NOTIFY_ON_EMPTY	(1ULL << 24)
#define	VIRTIO14_F_RESERVED_25		(1ULL << 25)
#define	VIRTIO14_F_RESERVED_26		(1ULL << 26)
#define	VIRTIO14_F_ANY_LAYOUT		(1ULL << 27)
#define	VIRTIO14_F_RING_INDIRECT_DESC	(1ULL << 28)
#define	VIRTIO14_F_RING_EVENT_IDX	(1ULL << 29)
#define	VIRTIO14_F_VERSION_1		(1ULL << 32)
#define	VIRTIO14_F_ACCESS_PLATFORM	(1ULL << 33)
#define	VIRTIO14_F_RING_PACKED		(1ULL << 34)
#define	VIRTIO14_F_IN_ORDER		(1ULL << 35)
#define	VIRTIO14_F_ORDER_PLATFORM	(1ULL << 36)
#define	VIRTIO14_F_SR_IOV		(1ULL << 37)
#define	VIRTIO14_F_NOTIFICATION_DATA	(1ULL << 38)
#define	VIRTIO14_F_NOTIF_CONFIG_DATA	(1ULL << 39)
#define	VIRTIO14_F_RING_RESET		(1ULL << 40)
#define	VIRTIO14_F_ADMIN_VQ		(1ULL << 41)
/* 5.1.3.2: legacy network-device feature bit 42. */
#define	VIRTIO14_NET_F_GUEST_RSC6	(1ULL << 42)
#define	VIRTIO14_F_SUSPEND		(1ULL << 43)
#define	VIRTIO14_F_RESERVED_44		(1ULL << 44)
#define	VIRTIO14_F_RESERVED_49		(1ULL << 49)
/* 2.2: endpoints of the device-specific feature allocations. */
#define	VIRTIO14_DEVICE_FEATURE_LOW_LAST	(1ULL << 23)
#define	VIRTIO14_DEVICE_FEATURE_HIGH_FIRST	(1ULL << 50)

/* 4.1.2: PCI Device Discovery. */
#define	VIRTIO14_PCI_VENDOR_ID		0x1af4U
#define	VIRTIO14_PCI_MODERN_DEVICE_BASE	0x1040U
#define	VIRTIO14_PCI_MODERN_SUBDEVICE_MIN	0x0040U
#define	VIRTIO14_PCI_REVISION		0x01U
#define	VIRTIO14_PCI_DEVICE_ID(type)	\
	(VIRTIO14_PCI_MODERN_DEVICE_BASE + (type))
#define	VIRTIO14_PCI_TRANSITIONAL_NETWORK	0x1000U
#define	VIRTIO14_PCI_TRANSITIONAL_BLOCK		0x1001U
#define	VIRTIO14_PCI_TRANSITIONAL_BALLOON	0x1002U
#define	VIRTIO14_PCI_TRANSITIONAL_CONSOLE	0x1003U
#define	VIRTIO14_PCI_TRANSITIONAL_SCSI		0x1004U
#define	VIRTIO14_PCI_TRANSITIONAL_ENTROPY	0x1005U
#define	VIRTIO14_PCI_TRANSITIONAL_9P		0x1009U

/* 4.1.3.1 and 4.2.2.2: device-configuration access widths. */
#define	VIRTIO14_CONFIG_FIELD_U8_SIZE	1U
#define	VIRTIO14_CONFIG_FIELD_U16_SIZE	2U
#define	VIRTIO14_CONFIG_FIELD_U32_SIZE	4U
#define	VIRTIO14_CONFIG_FIELD_U64_SIZE	8U
#define	VIRTIO14_CONFIG_MAX_ACCESS_SIZE	4U

/* 5: Device Types. */
#define	VIRTIO14_DEVICE_NETWORK		1U
#define	VIRTIO14_DEVICE_BLOCK		2U
#define	VIRTIO14_DEVICE_CONSOLE		3U
#define	VIRTIO14_DEVICE_ENTROPY		4U
#define	VIRTIO14_DEVICE_SCSI		8U
#define	VIRTIO14_DEVICE_9P		9U
#define	VIRTIO14_DEVICE_INPUT		18U
#define	VIRTIO14_DEVICE_VSOCK		19U

/* 4.1.4: Virtio Structure PCI Capabilities. */
#define	VIRTIO14_PCI_CAP_COMMON_CFG	1U
#define	VIRTIO14_PCI_CAP_NOTIFY_CFG	2U
#define	VIRTIO14_PCI_CAP_ISR_CFG	3U
#define	VIRTIO14_PCI_CAP_DEVICE_CFG	4U
#define	VIRTIO14_PCI_CAP_PCI_CFG	5U
#define	VIRTIO14_PCI_CAP_SHARED_MEMORY_CFG 8U
#define	VIRTIO14_PCI_CAP_VENDOR_CFG	9U
#define	VIRTIO14_PCI_CAP_SIZE		16U
#define	VIRTIO14_PCI_NOTIFY_CAP_SIZE	20U
#define	VIRTIO14_PCI_CFG_CAP_SIZE	20U
#define	VIRTIO14_PCI_CFG_DATA_OFF	16U
#define	VIRTIO14_PCI_CAP_VNDR_OFF	0U
#define	VIRTIO14_PCI_CAP_NEXT_OFF	1U
#define	VIRTIO14_PCI_CAP_LEN_OFF	2U
#define	VIRTIO14_PCI_CAP_CFG_TYPE_OFF	3U
#define	VIRTIO14_PCI_CAP_BAR_OFF	4U
#define	VIRTIO14_PCI_CAP_OFFSET_OFF	8U
#define	VIRTIO14_PCI_CAP_LENGTH_OFF	12U
#define	VIRTIO14_PCI_NOTIFY_MULT_OFF	16U
#define	VIRTIO14_PCI_MIN_BAR		0U
#define	VIRTIO14_PCI_MAX_BAR		5U
#define	VIRTIO14_PCI_NOTIFY_NO_DATA_SIZE	2U
#define	VIRTIO14_PCI_NOTIFY_DATA_SIZE	4U

/* 4.1.4.8: Transitional Device Legacy Interface register offsets. */
#define	VIRTIO14_LEGACY_DEVICE_FEATURES	0U
#define	VIRTIO14_LEGACY_DRIVER_FEATURES	4U
#define	VIRTIO14_LEGACY_QUEUE_ADDRESS	8U
#define	VIRTIO14_LEGACY_QUEUE_SIZE	12U
#define	VIRTIO14_LEGACY_QUEUE_SELECT	14U
#define	VIRTIO14_LEGACY_QUEUE_NOTIFY	16U
#define	VIRTIO14_LEGACY_DEVICE_STATUS	18U
#define	VIRTIO14_LEGACY_ISR_STATUS	19U
#define	VIRTIO14_LEGACY_CONFIG_MSIX_VECTOR 20U
#define	VIRTIO14_LEGACY_QUEUE_MSIX_VECTOR 22U
#define	VIRTIO14_LEGACY_DEVICE_CFG_OFF	20U
#define	VIRTIO14_LEGACY_MSIX_DEVICE_CFG_OFF 24U

/* 4.1.4.3: Common configuration structure byte offsets. */
#define	VIRTIO14_COMMON_DEVICE_FEATURE_SELECT	0U
#define	VIRTIO14_COMMON_DEVICE_FEATURE		4U
#define	VIRTIO14_COMMON_DRIVER_FEATURE_SELECT	8U
#define	VIRTIO14_COMMON_DRIVER_FEATURE		12U
#define	VIRTIO14_COMMON_CONFIG_MSIX_VECTOR	16U
#define	VIRTIO14_COMMON_NUM_QUEUES		18U
#define	VIRTIO14_COMMON_DEVICE_STATUS		20U
#define	VIRTIO14_COMMON_CONFIG_GENERATION	21U
#define	VIRTIO14_COMMON_QUEUE_SELECT		22U
#define	VIRTIO14_COMMON_QUEUE_SIZE		24U
#define	VIRTIO14_COMMON_QUEUE_MSIX_VECTOR	26U
#define	VIRTIO14_COMMON_QUEUE_ENABLE		28U
#define	VIRTIO14_COMMON_QUEUE_NOTIFY_OFF	30U
#define	VIRTIO14_COMMON_QUEUE_DESC		32U
#define	VIRTIO14_COMMON_QUEUE_DRIVER		40U
#define	VIRTIO14_COMMON_QUEUE_DEVICE		48U
#define	VIRTIO14_COMMON_BASE_SIZE		56U
#define	VIRTIO14_COMMON_QUEUE_NOTIF_CONFIG_DATA	56U
#define	VIRTIO14_COMMON_QUEUE_RESET		58U
#define	VIRTIO14_COMMON_ADMIN_QUEUE_INDEX	60U
#define	VIRTIO14_COMMON_ADMIN_QUEUE_NUM		62U

/* 4.1.4.4: Notification structure. */
#define	VIRTIO14_NOTIFICATION_VQ_INDEX_MASK	0xffffU
#define	VIRTIO14_NOTIFICATION_NEXT_OFF_SHIFT	16U
#define	VIRTIO14_NOTIFICATION_NEXT_WRAP_SHIFT	31U

/* 4.1.4.5: ISR status bits. */
#define	VIRTIO14_ISR_QUEUE		0x01U
#define	VIRTIO14_ISR_CONFIG		0x02U
#define	VIRTIO14_MSI_NO_VECTOR		0xffffU

/* 4.2.2: MMIO device register layout. */
#define	VIRTIO14_MMIO_MAGIC_VALUE	0x000U
#define	VIRTIO14_MMIO_VERSION		0x004U
#define	VIRTIO14_MMIO_DEVICE_ID		0x008U
#define	VIRTIO14_MMIO_VENDOR_ID		0x00cU
#define	VIRTIO14_MMIO_DEVICE_FEATURES	0x010U
#define	VIRTIO14_MMIO_DEVICE_FEATURES_SEL 0x014U
#define	VIRTIO14_MMIO_DRIVER_FEATURES	0x020U
#define	VIRTIO14_MMIO_DRIVER_FEATURES_SEL 0x024U
#define	VIRTIO14_MMIO_QUEUE_SEL		0x030U
#define	VIRTIO14_MMIO_QUEUE_NUM_MAX	0x034U
#define	VIRTIO14_MMIO_QUEUE_NUM		0x038U
#define	VIRTIO14_MMIO_QUEUE_READY	0x044U
#define	VIRTIO14_MMIO_QUEUE_NOTIFY	0x050U
#define	VIRTIO14_MMIO_INTERRUPT_STATUS	0x060U
#define	VIRTIO14_MMIO_INTERRUPT_ACK	0x064U
#define	VIRTIO14_MMIO_STATUS		0x070U
#define	VIRTIO14_MMIO_QUEUE_DESC_LOW	0x080U
#define	VIRTIO14_MMIO_QUEUE_DESC_HIGH	0x084U
#define	VIRTIO14_MMIO_QUEUE_DRIVER_LOW	0x090U
#define	VIRTIO14_MMIO_QUEUE_DRIVER_HIGH	0x094U
#define	VIRTIO14_MMIO_QUEUE_DEVICE_LOW	0x0a0U
#define	VIRTIO14_MMIO_QUEUE_DEVICE_HIGH	0x0a4U
#define	VIRTIO14_MMIO_QUEUE_RESET	0x0c0U
#define	VIRTIO14_MMIO_CONFIG_GENERATION	0x0fcU
#define	VIRTIO14_MMIO_CONFIG		0x100U
#define	VIRTIO14_MMIO_MAGIC_VIRT	0x74726976U
#define	VIRTIO14_MMIO_LEGACY_VERSION	1U
#define	VIRTIO14_MMIO_MODERN_VERSION	2U
#define	VIRTIO14_MMIO_INTERRUPT_VRING	0x01U
#define	VIRTIO14_MMIO_INTERRUPT_CONFIG	0x02U
#define	VIRTIO14_MMIO_CONTROL_ACCESS_SIZE 4U

/* 2.7: Split Virtqueues. */
#define	VIRTIO14_DESC_F_NEXT		0x01U
#define	VIRTIO14_DESC_F_WRITE		0x02U
#define	VIRTIO14_DESC_F_INDIRECT	0x04U
#define	VIRTIO14_USED_F_NO_NOTIFY	0x01U
#define	VIRTIO14_SPLIT_DESC_SIZE	16U
#define	VIRTIO14_SPLIT_AVAIL_HEADER_SIZE	4U
#define	VIRTIO14_SPLIT_AVAIL_ELEM_SIZE	2U
#define	VIRTIO14_SPLIT_EVENT_FIELD_SIZE	2U
#define	VIRTIO14_SPLIT_USED_HEADER_SIZE	4U
#define	VIRTIO14_SPLIT_USED_ELEM_SIZE	8U
#define	VIRTIO14_SPLIT_QUEUE_SIZE_MAX	32768U

/* 5.1.6 and 5.1.9: network feature and header values used by tests. */
#define	VIRTIO14_NET_F_CSUM		(1ULL << 0)
#define	VIRTIO14_NET_F_GUEST_CSUM	(1ULL << 1)
#define	VIRTIO14_NET_F_CTRL_GUEST_OFFLOADS (1ULL << 2)
#define	VIRTIO14_NET_F_MTU		(1ULL << 3)
#define	VIRTIO14_NET_F_MAC		(1ULL << 5)
#define	VIRTIO14_NET_F_GUEST_TSO4	(1ULL << 7)
#define	VIRTIO14_NET_F_GUEST_TSO6	(1ULL << 8)
#define	VIRTIO14_NET_F_GUEST_ECN	(1ULL << 9)
#define	VIRTIO14_NET_F_GUEST_UFO	(1ULL << 10)
#define	VIRTIO14_NET_F_HOST_TSO4	(1ULL << 11)
#define	VIRTIO14_NET_F_HOST_TSO6	(1ULL << 12)
#define	VIRTIO14_NET_F_HOST_ECN		(1ULL << 13)
#define	VIRTIO14_NET_F_HOST_UFO		(1ULL << 14)
#define	VIRTIO14_NET_F_MRG_RXBUF	(1ULL << 15)
#define	VIRTIO14_NET_F_STATUS		(1ULL << 16)
#define	VIRTIO14_NET_F_CTRL_VQ		(1ULL << 17)
#define	VIRTIO14_NET_F_MQ		(1ULL << 22)
#define	VIRTIO14_NET_F_HASH_REPORT	(1ULL << 57)
#define	VIRTIO14_NET_F_GUEST_HDRLEN	(1ULL << 59)
#define	VIRTIO14_NET_F_RSS		(1ULL << 60)
#define	VIRTIO14_NET_HDR_F_NEEDS_CSUM	0x01U
#define	VIRTIO14_NET_HDR_F_DATA_VALID	0x02U
#define	VIRTIO14_NET_HDR_F_UDP_TUNNEL_CSUM 0x08U
#define	VIRTIO14_NET_HDR_GSO_NONE	0x00U
#define	VIRTIO14_NET_HDR_GSO_TCPV4	0x01U
#define	VIRTIO14_NET_HDR_GSO_UDP	0x03U
#define	VIRTIO14_NET_HDR_GSO_TCPV6	0x04U
#define	VIRTIO14_NET_HDR_GSO_TUNNEL_IPV4 0x20U
#define	VIRTIO14_NET_HDR_GSO_TUNNEL_IPV6 0x40U
#define	VIRTIO14_NET_HDR_GSO_ECN	0x80U
#define	VIRTIO14_NET_LEGACY_HDR_SIZE	10U
#define	VIRTIO14_NET_MODERN_HDR_SIZE	12U
#define	VIRTIO14_NET_HASH_HDR_SIZE	20U
#define	VIRTIO14_NET_HDR_FLAGS_OFF	0U
#define	VIRTIO14_NET_HDR_GSO_TYPE_OFF	1U
#define	VIRTIO14_NET_HDR_HDR_LEN_OFF	2U
#define	VIRTIO14_NET_HDR_GSO_SIZE_OFF	4U
#define	VIRTIO14_NET_HDR_CSUM_START_OFF	6U
#define	VIRTIO14_NET_HDR_CSUM_OFFSET_OFF 8U
#define	VIRTIO14_NET_HDR_NUM_BUFFERS_OFF 10U
#define	VIRTIO14_NET_HDR_HASH_VALUE_OFF	12U
#define	VIRTIO14_NET_HDR_HASH_REPORT_OFF 16U
#define	VIRTIO14_NET_HDR_HASH_PADDING_OFF 18U
#define	VIRTIO14_NET_CONFIG_SIZE	24U
#define	VIRTIO14_NET_CONFIG_MAC_OFF	0U
#define	VIRTIO14_NET_CONFIG_MAC_SIZE	6U
#define	VIRTIO14_NET_CONFIG_STATUS_OFF	6U
#define	VIRTIO14_NET_CONFIG_MAX_PAIRS_OFF 8U
#define	VIRTIO14_NET_CONFIG_MTU_OFF	10U
#define	VIRTIO14_NET_CONFIG_SPEED_OFF	12U
#define	VIRTIO14_NET_CONFIG_DUPLEX_OFF	16U
#define	VIRTIO14_NET_CONFIG_RSS_KEY_SIZE_OFF 17U
#define	VIRTIO14_NET_CONFIG_RSS_TABLE_SIZE_OFF 18U
#define	VIRTIO14_NET_CONFIG_HASH_TYPES_OFF 20U
#define	VIRTIO14_NET_RECEIVEQ		0U
#define	VIRTIO14_NET_TRANSMITQ		1U
#define	VIRTIO14_NET_CONTROLQ		2U
#define	VIRTIO14_NET_RXQ(pair)		((pair) * 2U)
#define	VIRTIO14_NET_TXQ(pair)		((pair) * 2U + 1U)
#define	VIRTIO14_NET_MQ_CONTROLQ(max_pairs) ((max_pairs) * 2U)
#define	VIRTIO14_NET_CTRL_MQ		4U
#define	VIRTIO14_NET_CTRL_MQ_VQ_PAIRS_SET 0U
#define	VIRTIO14_NET_CTRL_MQ_RSS_CONFIG	1U
#define	VIRTIO14_NET_CTRL_MQ_HASH_CONFIG 2U
#define	VIRTIO14_NET_CTRL_MQ_PAIRS_MIN	1U
#define	VIRTIO14_NET_CTRL_MQ_PAIRS_MAX	0x8000U
#define	VIRTIO14_NET_CTRL_OK		0U
#define	VIRTIO14_NET_CTRL_ERR		1U
#define	VIRTIO14_NET_CTRL_CLASS_OFF	0U
#define	VIRTIO14_NET_CTRL_COMMAND_OFF	1U
#define	VIRTIO14_NET_CTRL_DATA_OFF	2U
#define	VIRTIO14_NET_CTRL_MQ_SIZE	4U
#define	VIRTIO14_NET_RSS_KEY_SIZE_MIN	40U
#define	VIRTIO14_NET_RSS_TABLE_SIZE_MIN	128U
#define	VIRTIO14_NET_RSS_HASH_TYPE_IPV4	(1U << 0)
#define	VIRTIO14_NET_RSS_HASH_TYPE_TCPV4 (1U << 1)
#define	VIRTIO14_NET_RSS_HASH_TYPE_UDPV4 (1U << 2)
#define	VIRTIO14_NET_RSS_HASH_TYPE_IPV6	(1U << 3)
#define	VIRTIO14_NET_RSS_HASH_TYPE_TCPV6 (1U << 4)
#define	VIRTIO14_NET_RSS_HASH_TYPE_UDPV6 (1U << 5)
#define	VIRTIO14_NET_RSS_HASH_TYPES_BASIC ((1U << 6) - 1)
#define	VIRTIO14_NET_RSS_HASH_TYPES_OFF	2U
#define	VIRTIO14_NET_RSS_TABLE_MASK_OFF	6U
#define	VIRTIO14_NET_RSS_UNCLASSIFIED_OFF 8U
#define	VIRTIO14_NET_RSS_TABLE_OFF	10U
#define	VIRTIO14_NET_RSS_COMMAND_MIN	15U
#define	VIRTIO14_NET_RSS_COMMAND_MAX	(13U + \
	    VIRTIO14_NET_RSS_TABLE_SIZE_MIN * 2U + \
	    VIRTIO14_NET_RSS_KEY_SIZE_MIN)
/*
 * Linux includes the natural-alignment tail byte from its RSS trailer
 * structure in the control descriptor.  This is an interoperability size,
 * not a value derived from the packed VirtIO wire-field layout above.
 */
#define	VIRTIO14_LINUX_NET_RSS_COMMAND_MAX	310U
#define	VIRTIO14_NET_HASH_COMMAND_MIN	15U
#define	VIRTIO14_NET_HASH_COMMAND_MAX	(15U + \
	    VIRTIO14_NET_RSS_KEY_SIZE_MIN)
#define	VIRTIO14_LINUX_NET_HASH_COMMAND_MAX	56U
#define	VIRTIO14_NET_HASH_TYPES_OFF	2U
#define	VIRTIO14_NET_HASH_RESERVED_OFF	6U
#define	VIRTIO14_NET_HASH_RESERVED_SIZE	8U
#define	VIRTIO14_NET_HASH_KEY_LENGTH_OFF 14U
#define	VIRTIO14_NET_HASH_KEY_OFF	15U
#define	VIRTIO14_NET_HASH_REPORT_NONE	0U
#define	VIRTIO14_NET_HASH_REPORT_IPV4	1U
#define	VIRTIO14_NET_HASH_REPORT_TCPV4	2U
#define	VIRTIO14_NET_HASH_REPORT_UDPV4	3U
#define	VIRTIO14_NET_HASH_REPORT_IPV6	4U
#define	VIRTIO14_NET_HASH_REPORT_TCPV6	5U
#define	VIRTIO14_NET_HASH_REPORT_UDPV6	6U
#define	VIRTIO14_NET_MTU_MIN		68U
#define	VIRTIO14_NET_MTU_MAX		65535U
#define	VIRTIO14_NET_SINGLE_BUFFER_COUNT 1U
/* 5.1.9.3: maximum incoming GSO packet and base-header record size. */
#define	VIRTIO14_NET_MAX_GSO_PACKET_SIZE 65589U
#define	VIRTIO14_NET_MAX_BASE_RECORD_SIZE \
	(VIRTIO14_NET_MAX_GSO_PACKET_SIZE + VIRTIO14_NET_MODERN_HDR_SIZE)

/* 5.2.6: block request types and status values used by tests. */
#define	VIRTIO14_BLK_F_BARRIER		(1ULL << 0)
#define	VIRTIO14_BLK_F_RO		(1ULL << 5)
#define	VIRTIO14_BLK_F_FLUSH		(1ULL << 9)
#define	VIRTIO14_BLK_F_CONFIG_WCE	(1ULL << 11)
#define	VIRTIO14_BLK_F_MQ		(1ULL << 12)
#define	VIRTIO14_BLK_F_DISCARD		(1ULL << 13)
#define	VIRTIO14_BLK_F_WRITE_ZEROES	(1ULL << 14)
#define	VIRTIO14_BLK_T_BARRIER		0x80000000U
#define	VIRTIO14_BLK_T_IN		0U
#define	VIRTIO14_BLK_T_OUT		1U
#define	VIRTIO14_BLK_T_FLUSH		4U
#define	VIRTIO14_BLK_T_GET_ID		8U
#define	VIRTIO14_BLK_T_DISCARD		11U
#define	VIRTIO14_BLK_T_WRITE_ZEROES	13U
#define	VIRTIO14_BLK_S_OK		0U
#define	VIRTIO14_BLK_S_IOERR		1U
#define	VIRTIO14_BLK_S_UNSUPP		2U
#define	VIRTIO14_BLK_ID_BYTES		20U
#define	VIRTIO14_BLK_SECTOR_BYTES	512U
#define	VIRTIO14_BLK_REQUEST_HEADER_SIZE 16U
#define	VIRTIO14_BLK_REQUEST_TYPE_OFF	0U
#define	VIRTIO14_BLK_REQUEST_RESERVED_OFF 4U
#define	VIRTIO14_BLK_REQUEST_SECTOR_OFF	8U
#define	VIRTIO14_BLK_STATUS_SIZE	1U
#define	VIRTIO14_BLK_DISCARD_SEGMENT_SIZE 16U
#define	VIRTIO14_BLK_DISCARD_SECTOR_OFF	0U
#define	VIRTIO14_BLK_DISCARD_NUM_SECTORS_OFF 8U
#define	VIRTIO14_BLK_DISCARD_FLAGS_OFF	12U
#define	VIRTIO14_BLK_WRITE_ZEROES_FLAG_UNMAP 1U
#define	VIRTIO14_BLK_CONFIG_SIZE	60U
#define	VIRTIO14_BLK_CONFIG_CAPACITY_OFF 0U
#define	VIRTIO14_BLK_CONFIG_SIZE_MAX_OFF 8U
#define	VIRTIO14_BLK_CONFIG_SEG_MAX_OFF	12U
#define	VIRTIO14_BLK_CONFIG_GEOMETRY_OFF 16U
#define	VIRTIO14_BLK_CONFIG_BLK_SIZE_OFF 20U
#define	VIRTIO14_BLK_CONFIG_TOPOLOGY_OFF 24U
#define	VIRTIO14_BLK_CONFIG_WRITEBACK_OFF 32U
#define	VIRTIO14_BLK_CONFIG_NUM_QUEUES_OFF 34U
#define	VIRTIO14_BLK_CONFIG_MAX_DISCARD_SECTORS_OFF 36U
#define	VIRTIO14_BLK_CONFIG_MAX_DISCARD_SEG_OFF 40U
#define	VIRTIO14_BLK_CONFIG_DISCARD_ALIGN_OFF 44U
#define	VIRTIO14_BLK_CONFIG_MAX_WRITE_ZEROES_SECTORS_OFF 48U
#define	VIRTIO14_BLK_CONFIG_MAX_WRITE_ZEROES_SEG_OFF 52U
#define	VIRTIO14_BLK_CONFIG_WRITE_ZEROES_MAY_UNMAP_OFF 56U

/* 5.3: Console Device. */
#define	VIRTIO14_CONSOLE_F_SIZE_BIT	0U
#define	VIRTIO14_CONSOLE_F_MULTIPORT_BIT	1U
#define	VIRTIO14_CONSOLE_F_EMERG_WRITE_BIT 2U
#define	VIRTIO14_CONSOLE_F_SIZE		(1ULL << 0)
#define	VIRTIO14_CONSOLE_F_MULTIPORT	(1ULL << 1)
#define	VIRTIO14_CONSOLE_F_EMERG_WRITE	(1ULL << 2)
#define	VIRTIO14_CONSOLE_DEVICE_READY	0U
#define	VIRTIO14_CONSOLE_DEVICE_ADD	1U
#define	VIRTIO14_CONSOLE_DEVICE_REMOVE	2U
#define	VIRTIO14_CONSOLE_PORT_READY	3U
#define	VIRTIO14_CONSOLE_CONSOLE_PORT	4U
#define	VIRTIO14_CONSOLE_RESIZE		5U
#define	VIRTIO14_CONSOLE_PORT_OPEN	6U
#define	VIRTIO14_CONSOLE_PORT_NAME	7U
#define	VIRTIO14_CONSOLE_CONFIG_SIZE	12U
#define	VIRTIO14_CONSOLE_CONFIG_COLS_OFF	0U
#define	VIRTIO14_CONSOLE_CONFIG_ROWS_OFF	2U
#define	VIRTIO14_CONSOLE_CONFIG_MAX_PORTS_OFF 4U
#define	VIRTIO14_CONSOLE_CONFIG_EMERG_WR_OFF 8U
#define	VIRTIO14_CONSOLE_CONTROL_SIZE	8U
#define	VIRTIO14_CONSOLE_CONTROL_ID_OFF	0U
#define	VIRTIO14_CONSOLE_CONTROL_EVENT_OFF 4U
#define	VIRTIO14_CONSOLE_CONTROL_VALUE_OFF 6U

/* 5.6.3: SCSI feature bits. */
#define	VIRTIO14_SCSI_F_HOTPLUG_BIT	1U
#define	VIRTIO14_SCSI_F_CHANGE_BIT	2U
#define	VIRTIO14_SCSI_F_HOTPLUG		(1ULL << 1)
#define	VIRTIO14_SCSI_F_CHANGE		(1ULL << 2)

/* 5.6.6.2 and 5.6.6.3: SCSI control and command responses. */
#define	VIRTIO14_SCSI_LUN_ADDRESS_METHOD	0x01U
#define	VIRTIO14_SCSI_T_TMF		0U
#define	VIRTIO14_SCSI_T_TMF_ABORT_TASK	0U
#define	VIRTIO14_SCSI_T_AN_QUERY	1U
#define	VIRTIO14_SCSI_T_AN_SUBSCRIBE	2U
#define	VIRTIO14_SCSI_S_FUNCTION_COMPLETE 0U
#define	VIRTIO14_SCSI_S_FUNCTION_SUCCEEDED 10U
#define	VIRTIO14_SCSI_S_FUNCTION_REJECTED 11U
#define	VIRTIO14_SCSI_S_OK		0U
#define	VIRTIO14_SCSI_S_OVERRUN		1U
#define	VIRTIO14_SCSI_S_ABORTED		2U
#define	VIRTIO14_SCSI_S_BAD_TARGET	3U
#define	VIRTIO14_SCSI_S_RESET		4U
#define	VIRTIO14_SCSI_S_TRANSPORT_FAILURE 6U
#define	VIRTIO14_SCSI_S_FAILURE		9U
#define	VIRTIO14_SCSI_DEFAULT_SENSE_SIZE 96U
#define	VIRTIO14_SCSI_DEFAULT_CDB_SIZE	32U
#define	VIRTIO14_SCSI_SECTOR_BYTES	512U
#define	VIRTIO14_SCSI_MAX_CHANNEL	0U
#define	VIRTIO14_SCSI_MAX_TARGET_LIMIT	255U
#define	VIRTIO14_SCSI_MAX_LUN_LIMIT	16383U
#define	VIRTIO14_SCSI_CONFIG_SIZE	36U
#define	VIRTIO14_SCSI_CONFIG_NUM_QUEUES_OFF 0U
#define	VIRTIO14_SCSI_CONFIG_SEG_MAX_OFF	4U
#define	VIRTIO14_SCSI_CONFIG_MAX_SECTORS_OFF 8U
#define	VIRTIO14_SCSI_CONFIG_CMD_PER_LUN_OFF 12U
#define	VIRTIO14_SCSI_CONFIG_EVENT_INFO_SIZE_OFF 16U
#define	VIRTIO14_SCSI_CONFIG_SENSE_SIZE_OFF 20U
#define	VIRTIO14_SCSI_CONFIG_CDB_SIZE_OFF 24U
#define	VIRTIO14_SCSI_CONFIG_MAX_CHANNEL_OFF 28U
#define	VIRTIO14_SCSI_CONFIG_MAX_TARGET_OFF 30U
#define	VIRTIO14_SCSI_CONFIG_MAX_LUN_OFF	32U
#define	VIRTIO14_SCSI_TMF_REQUEST_SIZE	24U
#define	VIRTIO14_SCSI_TMF_TYPE_OFF	0U
#define	VIRTIO14_SCSI_TMF_SUBTYPE_OFF	4U
#define	VIRTIO14_SCSI_TMF_LUN_OFF	8U
#define	VIRTIO14_SCSI_TMF_ID_OFF	16U
#define	VIRTIO14_SCSI_TMF_RESPONSE_OFF	24U
#define	VIRTIO14_SCSI_TMF_RESPONSE_SIZE	1U
#define	VIRTIO14_SCSI_AN_REQUEST_SIZE	16U
#define	VIRTIO14_SCSI_AN_EVENT_ACTUAL_OFF 16U
#define	VIRTIO14_SCSI_AN_EVENT_ACTUAL_SIZE 4U
#define	VIRTIO14_SCSI_AN_RESPONSE_OFF	20U
#define	VIRTIO14_SCSI_AN_RESPONSE_SIZE	1U
#define	VIRTIO14_SCSI_EVENT_SIZE	16U
#define	VIRTIO14_SCSI_EVENT_EVENT_OFF	0U
#define	VIRTIO14_SCSI_EVENT_LUN_OFF	4U
#define	VIRTIO14_SCSI_EVENT_REASON_OFF	12U
#define	VIRTIO14_SCSI_CMD_REQUEST_FIXED_SIZE 19U
#define	VIRTIO14_SCSI_LUN_SIZE		8U
#define	VIRTIO14_SCSI_CMD_REQUEST_LUN_OFF 0U
#define	VIRTIO14_SCSI_CMD_REQUEST_ID_OFF	8U
#define	VIRTIO14_SCSI_CMD_REQUEST_ID_SIZE 8U
#define	VIRTIO14_SCSI_CMD_REQUEST_TASK_ATTR_OFF 16U
#define	VIRTIO14_SCSI_CMD_REQUEST_PRIO_OFF 17U
#define	VIRTIO14_SCSI_CMD_REQUEST_CRN_OFF 18U
#define	VIRTIO14_SCSI_CMD_REQUEST_CDB_OFF 19U
#define	VIRTIO14_SCSI_DEFAULT_CMD_REQUEST_SIZE \
	(VIRTIO14_SCSI_CMD_REQUEST_FIXED_SIZE + \
	VIRTIO14_SCSI_DEFAULT_CDB_SIZE)
#define	VIRTIO14_SCSI_CMD_RESPONSE_FIXED_SIZE 12U
#define	VIRTIO14_SCSI_CMD_RESPONSE_SENSE_LEN_OFF 0U
#define	VIRTIO14_SCSI_CMD_RESPONSE_RESIDUAL_OFF 4U
#define	VIRTIO14_SCSI_CMD_RESPONSE_STATUS_QUALIFIER_OFF 8U
#define	VIRTIO14_SCSI_CMD_RESPONSE_STATUS_OFF 10U
#define	VIRTIO14_SCSI_CMD_RESPONSE_RESPONSE_OFF 11U
#define	VIRTIO14_SCSI_CMD_RESPONSE_SENSE_OFF 12U
#define	VIRTIO14_SCSI_DEFAULT_CMD_RESPONSE_SIZE \
	(VIRTIO14_SCSI_CMD_RESPONSE_FIXED_SIZE + \
	VIRTIO14_SCSI_DEFAULT_SENSE_SIZE)

/* 5.9.4: 9P device configuration. */
#define	VIRTIO14_9P_F_MOUNT_TAG		(1ULL << 0)
#define	VIRTIO14_9P_CONFIG_TAG_LEN_SIZE	2U
#define	VIRTIO14_9P_CONFIG_TAG_LEN_OFF	0U

/* 5.8.4 and 5.8.6: Input Device configuration and event wire format. */
#define	VIRTIO14_INPUT_CFG_UNSET	0x00U
#define	VIRTIO14_INPUT_CFG_ID_NAME	0x01U
#define	VIRTIO14_INPUT_CFG_ID_SERIAL	0x02U
#define	VIRTIO14_INPUT_CFG_ID_DEVIDS	0x03U
#define	VIRTIO14_INPUT_CFG_PROP_BITS	0x10U
#define	VIRTIO14_INPUT_CFG_EV_BITS	0x11U
#define	VIRTIO14_INPUT_CFG_ABS_INFO	0x12U
#define	VIRTIO14_INPUT_CONFIG_SIZE	136U
#define	VIRTIO14_INPUT_CONFIG_SELECT_OFF 0U
#define	VIRTIO14_INPUT_CONFIG_SUBSEL_OFF 1U
#define	VIRTIO14_INPUT_CONFIG_SIZE_OFF	2U
#define	VIRTIO14_INPUT_CONFIG_UNION_OFF	8U
#define	VIRTIO14_INPUT_CONFIG_RESERVED_SIZE 5U
#define	VIRTIO14_INPUT_CONFIG_UNION_SIZE 128U
#define	VIRTIO14_INPUT_CONFIG_STRING_SIZE 128U
#define	VIRTIO14_INPUT_ABSINFO_SIZE	20U
#define	VIRTIO14_INPUT_DEVIDS_SIZE	8U
#define	VIRTIO14_INPUT_EVENT_SIZE	8U
#define	VIRTIO14_INPUT_EVENT_TYPE_OFF	0U
#define	VIRTIO14_INPUT_EVENT_CODE_OFF	2U
#define	VIRTIO14_INPUT_EVENT_VALUE_OFF	4U
#define	VIRTIO14_INPUT_EVENTQ		0U
#define	VIRTIO14_INPUT_STATUSQ		1U

/* 5.10: Socket Device feature bits and packet fields. */
#define	VIRTIO14_VSOCK_F_STREAM		(1ULL << 0)
#define	VIRTIO14_VSOCK_F_SEQPACKET	(1ULL << 1)
#define	VIRTIO14_VSOCK_F_NO_IMPLIED_STREAM (1ULL << 2)
#define	VIRTIO14_VSOCK_RECEIVEQ		0U
#define	VIRTIO14_VSOCK_TRANSMITQ	1U
#define	VIRTIO14_VSOCK_EVENTQ		2U
#define	VIRTIO14_VSOCK_CID_RESERVED_0	0ULL
#define	VIRTIO14_VSOCK_CID_RESERVED_1	1ULL
#define	VIRTIO14_VSOCK_CID_HOST		2ULL
#define	VIRTIO14_VSOCK_CONFIG_SIZE	8U
#define	VIRTIO14_VSOCK_CONFIG_GUEST_CID_OFF 0U
#define	VIRTIO14_VSOCK_TYPE_STREAM	1U
#define	VIRTIO14_VSOCK_TYPE_SEQPACKET	2U
#define	VIRTIO14_VSOCK_OP_INVALID	0U
#define	VIRTIO14_VSOCK_OP_REQUEST	1U
#define	VIRTIO14_VSOCK_OP_RESPONSE	2U
#define	VIRTIO14_VSOCK_OP_RST		3U
#define	VIRTIO14_VSOCK_OP_SHUTDOWN	4U
#define	VIRTIO14_VSOCK_OP_RW		5U
#define	VIRTIO14_VSOCK_OP_CREDIT_UPDATE	6U
#define	VIRTIO14_VSOCK_OP_CREDIT_REQUEST 7U
#define	VIRTIO14_VSOCK_SHUTDOWN_RECEIVE	0x01U
#define	VIRTIO14_VSOCK_SHUTDOWN_SEND	0x02U
#define	VIRTIO14_VSOCK_SEQ_EOM		0x01U
#define	VIRTIO14_VSOCK_SEQ_EOR		0x02U
#define	VIRTIO14_VSOCK_HEADER_SIZE	44U
#define	VIRTIO14_VSOCK_HDR_SRC_CID_OFF	0U
#define	VIRTIO14_VSOCK_HDR_DST_CID_OFF	8U
#define	VIRTIO14_VSOCK_HDR_SRC_PORT_OFF	16U
#define	VIRTIO14_VSOCK_HDR_DST_PORT_OFF	20U
#define	VIRTIO14_VSOCK_HDR_LEN_OFF	24U
#define	VIRTIO14_VSOCK_HDR_TYPE_OFF	28U
#define	VIRTIO14_VSOCK_HDR_OP_OFF	30U
#define	VIRTIO14_VSOCK_HDR_FLAGS_OFF	32U
#define	VIRTIO14_VSOCK_HDR_BUF_ALLOC_OFF 36U
#define	VIRTIO14_VSOCK_HDR_FWD_CNT_OFF	40U

#endif /* _VIRTIO_1_4_SPEC_H_ */
