#!/bin/sh
#

# PROVIDE: oracled
# REQUIRE: FILESYSTEMS devd syslogd
# BEFORE: SERVERS
# KEYWORD: shutdown

. /etc/rc.subr

name="oracled"
desc="Oracle capability-world service manager"
rcvar="oracled_enable"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name

: ${oracled_enable:="YES"}
: ${oracled_flags:=""}

run_rc_command "$1"
