/*-
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <sys/types.h>
#include <sys/ioccom.h>

#include <dev/vmm/vmm_dev.h>

#include <atf-c.h>
#include <stddef.h>
#include <stdint.h>

#define	TEST_REQUEST_VERSION	UINT16_C(1)
#define	TEST_REQUEST_SIZE	UINT16_C(48)
#define	TEST_IOCTL_NUMBER	UINT32_C(116)
#define	TEST_RUN_IOCTL_NUMBER	UINT32_C(117)
#define	TEST_RUN_REQUEST_SIZE	UINT16_C(64)

ATF_TC_WITHOUT_HEAD(layout);
ATF_TC_BODY(layout, tc)
{
	struct vmm_startup_request request;

	ATF_REQUIRE_EQ(sizeof(request), TEST_REQUEST_SIZE);
	ATF_REQUIRE_EQ(offsetof(struct vmm_startup_request, version), 0);
	ATF_REQUIRE_EQ(offsetof(struct vmm_startup_request, operation), 4);
	ATF_REQUIRE_EQ(offsetof(struct vmm_startup_request, generation), 8);
	ATF_REQUIRE_EQ(offsetof(struct vmm_startup_request, expected_vcpus), 16);
	ATF_REQUIRE_EQ(offsetof(struct vmm_startup_request, reserved8), 28);
}

ATF_TC_WITHOUT_HEAD(constants);
ATF_TC_BODY(constants, tc)
{

	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_VERSION, TEST_REQUEST_VERSION);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_SIZE, TEST_REQUEST_SIZE);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_CONFIGURE, 1);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_WAIT_READY, 2);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_COMMIT, 3);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_STATUS, 4);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_PHASE_OPEN, 0);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_PHASE_COLLECTING, 1);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_PHASE_COMMITTED, 2);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_OWNER_USERSPACE, 0);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_OWNER_KERNEL, 1);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_EXECUTION_USERSPACE, 0);
	ATF_REQUIRE_EQ(VMM_STARTUP_REQUEST_EXECUTION_PRESTARTED, 1);
	ATF_REQUIRE_EQ(VM_STARTUP_REQUEST & 0xff,
	    TEST_IOCTL_NUMBER);
	ATF_REQUIRE_EQ(IOCGROUP(VM_STARTUP_REQUEST), 'v');
	ATF_REQUIRE_EQ(IOCPARM_LEN(VM_STARTUP_REQUEST), TEST_REQUEST_SIZE);
	ATF_REQUIRE((VM_STARTUP_REQUEST & IOC_DIRMASK & IOC_IN) != 0);
	ATF_REQUIRE((VM_STARTUP_REQUEST & IOC_DIRMASK & IOC_OUT) != 0);
	ATF_REQUIRE_EQ(VM_RUN_GENERATION & 0xff, TEST_RUN_IOCTL_NUMBER);
	ATF_REQUIRE_EQ(IOCGROUP(VM_RUN_GENERATION), 'v');
	ATF_REQUIRE_EQ(IOCPARM_LEN(VM_RUN_GENERATION),
	    TEST_RUN_REQUEST_SIZE);
	ATF_REQUIRE((VM_RUN_GENERATION & IOC_DIRMASK & IOC_IN) != 0);
	ATF_REQUIRE((VM_RUN_GENERATION & IOC_DIRMASK & IOC_OUT) == 0);
}

ATF_TP_ADD_TCS(tp)
{

	ATF_TP_ADD_TC(tp, layout);
	ATF_TP_ADD_TC(tp, constants);
	return (atf_no_error());
}
